# Generated by Django 4.2.29 on 2026-03-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_avatar_public_id_remove_user_avatar_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordtoken',
            name='platform',
            field=models.CharField(choices=[('WEB', 'Website'), ('APP', 'Application')], default='WEB', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_name',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('EMPLOYER', 'Employer'), ('JOB_SEEKER', 'Job Seeker')], default='JOB_SEEKER', max_length=10),
        ),
    ]
