/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  typescript: {
    // StaticImageData vs string mismatches from Vite→Next.js migration
    // These are runtime-safe and should be fixed incrementally
    ignoreBuildErrors: true,
  },
  output: 'standalone',
  serverExternalPackages: ['pdfjs-dist', '@react-pdf-viewer/core', '@react-pdf-viewer/get-file', '@react-pdf-viewer/zoom'],
  transpilePackages: [
    'swiper',
    'mui-image',
    'leaflet',
    'react-draft-wysiwyg',
    'react-image-gallery',
    'react-toastify',
    'sweetalert2',
  ],
  async rewrites() {
    return [
      { source: '/dang-nhap', destination: '/login' },
      { source: '/dang-ky', destination: '/register' },
      { source: '/quen-mat-khau', destination: '/forgot-password' },
      { source: '/xac-nhan-email', destination: '/email-verification-required' },
      { source: '/cap-nhat-mat-khau/:path*', destination: '/reset-password/:path*' },
      { source: '/viec-lam', destination: '/jobs' },
      { source: '/viec-lam/:slug', destination: '/jobs/:slug' },
      { source: '/cong-ty', destination: '/companies' },
      { source: '/cong-ty/:slug', destination: '/companies/:slug' },
      { source: '/ve-chung-toi', destination: '/about-us' },
      { source: '/viec-lam-theo-nganh-nghe', destination: '/jobs-by-career' },
      { source: '/viec-lam-theo-tinh-thanh', destination: '/jobs-by-city' },
      { source: '/viec-lam-theo-hinh-thuc-lam-viec', destination: '/jobs-by-type' },
      { source: '/bang-dieu-khien', destination: '/dashboard' },
      { source: '/ho-so', destination: '/profile' },
      { source: '/ho-so-tung-buoc/:slug', destination: '/online-profile/:slug' },
      { source: '/ho-so-dinh-kem/:slug', destination: '/attached-profile/:slug' },
      { source: '/viec-lam-cua-toi', destination: '/my-jobs' },
      { source: '/cong-ty-cua-toi', destination: '/my-company' },
      { source: '/phong-van-cua-toi', destination: '/my-interviews' },
      { source: '/thong-bao', destination: '/notifications' },
      { source: '/tai-khoan', destination: '/account' },
      { source: '/ket-noi-voi-nha-tuyen-dung', destination: '/chat' },

      { source: '/nha-tuyen-dung/login', destination: '/employer/login' },
      { source: '/nha-tuyen-dung/register', destination: '/employer/register' },
      { source: '/nha-tuyen-dung/forgot-password', destination: '/employer/forgot-password' },
      { source: '/nha-tuyen-dung/reset-password/:path*', destination: '/employer/reset-password/:path*' },
      { source: '/nha-tuyen-dung/gioi-thieu', destination: '/employer/introduce' },
      { source: '/nha-tuyen-dung/dich-vu', destination: '/employer/service' },
      { source: '/nha-tuyen-dung/bao-gia', destination: '/employer/pricing' },
      { source: '/nha-tuyen-dung/ho-tro', destination: '/employer/support' },
      { source: '/nha-tuyen-dung/blog-tuyen-dung', destination: '/employer/blog' },
      { source: '/nha-tuyen-dung', destination: '/employer/dashboard' },
      { source: '/nha-tuyen-dung/bang-dieu-khien', destination: '/employer/dashboard' },
      { source: '/nha-tuyen-dung/tin-tuyen-dung', destination: '/employer/job-posts' },
      { source: '/nha-tuyen-dung/ho-so-ung-tuyen', destination: '/employer/applied-profiles' },
      { source: '/nha-tuyen-dung/ho-so-da-luu', destination: '/employer/saved-profiles' },
      { source: '/nha-tuyen-dung/danh-sach-ung-vien', destination: '/employer/candidates' },
      { source: '/nha-tuyen-dung/chi-tiet-ung-vien/:slug', destination: '/employer/candidates/:slug' },
      { source: '/nha-tuyen-dung/cong-ty', destination: '/employer/company' },
      { source: '/nha-tuyen-dung/nhan-su-va-vai-tro', destination: '/employer/employees' },
      { source: '/nha-tuyen-dung/thong-bao', destination: '/employer/notifications' },
      { source: '/nha-tuyen-dung/tai-khoan', destination: '/employer/account' },
      { source: '/nha-tuyen-dung/cai-dat', destination: '/employer/settings' },
      { source: '/nha-tuyen-dung/ket-noi-voi-ung-vien', destination: '/employer/chat' },
      { source: '/nha-tuyen-dung/danh-sach-phong-van', destination: '/employer/interviews' },
      { source: '/nha-tuyen-dung/ngan-hang-cau-hoi', destination: '/employer/question-bank' },
      { source: '/nha-tuyen-dung/bo-cau-hoi', destination: '/employer/question-groups' },
      { source: '/nha-tuyen-dung/xac-thuc-nha-tuyen-dung', destination: '/employer/verification' },

      { source: '/nha-tuyen-dung/phong-van-ung-vien-truc-tiep', destination: '/employer/interviews/live' },
      { source: '/nha-tuyen-dung/phong-van-truc-tiep/:id', destination: '/employer/interviews/:id' },
      { source: '/nha-tuyen-dung/len-lich-phong-van', destination: '/employer/interviews/create' },
      { source: '/nha-tuyen-dung/chi-tiet-phong-van/:id', destination: '/employer/interviews/:id' },
      { source: '/quan-tri', destination: '/admin/dashboard' },
      { source: '/quan-tri/:path*', destination: '/admin/:path*' },
      { source: '/phong-van/room/:id', destination: '/interview/:id' },
      { source: '/phong-van/:path*', destination: '/interview/:path*' },
    ];
  },
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '**',
      },
      {
        protocol: 'http',
        hostname: '**',
      },
    ],
  },
};

export default nextConfig;
