ARG FRAPPE_BRANCH=version-16
ARG FRAPPE_IMAGE_PREFIX=frappe

FROM ${FRAPPE_IMAGE_PREFIX}/build:${FRAPPE_BRANCH} AS builder

ARG FRAPPE_BRANCH=version-16
ARG CACHE_BUST=""

USER root

COPY --chown=frappe:frappe vendor/frappe/frappe /opt/frappe/local/frappe
COPY --chown=frappe:frappe vendor/frappe/erpnext /opt/frappe/local/erpnext
COPY --chown=frappe:frappe vendor/frappe/hrms /opt/frappe/local/hrms
COPY --chown=frappe:frappe vendor/frappe/square_hrm_branding /opt/frappe/local/square_hrm_branding
COPY --chown=frappe:frappe infra/frappe-hrms/apps.json /opt/frappe/apps.json

USER frappe

RUN for entry in \
    "/opt/frappe/local/frappe version-16" \
    "/opt/frappe/local/erpnext version-16" \
    "/opt/frappe/local/hrms version-16" \
    "/opt/frappe/local/square_hrm_branding main"; \
  do \
    set -- ${entry}; \
    repo="$1"; \
    branch="$2"; \
    git -C "$repo" init -b "$branch"; \
    git -C "$repo" config user.email "engineering@square.vn"; \
    git -C "$repo" config user.name "Square Build"; \
    git -C "$repo" add -A; \
    git -C "$repo" commit -q -m "Initialize local source"; \
  done

RUN : "${CACHE_BUST}" && \
  bench init --apps_path=/opt/frappe/apps.json \
    --frappe-branch=${FRAPPE_BRANCH} \
    --frappe-path=/opt/frappe/local/frappe \
    --no-procfile \
    --no-backups \
    --skip-redis-config-generation \
    --verbose \
    /home/frappe/frappe-bench && \
  cd /home/frappe/frappe-bench && \
  echo "{}" > sites/common_site_config.json && \
  ln -sfn /home/frappe/frappe-bench/apps/square_hrm_branding/square_hrm_branding/public sites/assets/square_hrm_branding && \
  find apps -mindepth 1 -path "*/.git" | xargs rm -fr

FROM ${FRAPPE_IMAGE_PREFIX}/base:${FRAPPE_BRANCH} AS backend

USER frappe

COPY --from=builder --chown=frappe:frappe /home/frappe/frappe-bench /home/frappe/frappe-bench

WORKDIR /home/frappe/frappe-bench

RUN cp -r /home/frappe/frappe-bench/sites/assets /home/frappe/frappe-bench/assets && \
  rm -rf /home/frappe/frappe-bench/sites/assets

VOLUME [ \
  "/home/frappe/frappe-bench/sites", \
  "/home/frappe/frappe-bench/logs" \
]

USER root
COPY vendor/frappe/frappe_docker/resources/core/main-entrypoint.sh /usr/local/bin/entrypoint.sh
COPY vendor/frappe/frappe_docker/resources/core/nginx/nginx-template.conf /templates/nginx/frappe.conf.template
RUN sed -i 's/\r$//' /usr/local/bin/entrypoint.sh && \
  chmod 755 /usr/local/bin/entrypoint.sh

USER frappe
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD [ \
  "/home/frappe/frappe-bench/env/bin/gunicorn", \
  "--chdir=/home/frappe/frappe-bench/sites", \
  "--bind=0.0.0.0:8000", \
  "--threads=4", \
  "--workers=2", \
  "--worker-class=gthread", \
  "--worker-tmp-dir=/dev/shm", \
  "--timeout=120", \
  "--preload", \
  "frappe.app:application" \
]
