# Generated by Codex on 2026-05-16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("status_change", "Status change"),
                            ("bulk_status", "Bulk status"),
                            ("agent_access", "Agent access"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("actor_email", models.EmailField(blank=True, default="", max_length=254)),
                ("resource_type", models.CharField(db_index=True, max_length=120)),
                ("resource_id", models.CharField(blank=True, db_index=True, default="", max_length=80)),
                ("resource_repr", models.CharField(blank=True, default="", max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("request_method", models.CharField(blank=True, default="", max_length=12)),
                ("request_path", models.CharField(blank=True, default="", max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "project_common_audit_log",
                "ordering": ["-create_at"],
            },
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["resource_type", "resource_id"], name="project_com_resourc_bdcf28_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["actor", "create_at"], name="project_com_actor_i_3c30e8_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["action", "create_at"], name="project_com_action_ddc99e_idx"),
        ),
    ]
