# Generated by Django 4.2.29 on 2026-03-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_city_code_district_code_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='is_hot',
            field=models.BooleanField(default=False),
        ),
    ]
