# Generated by Django 4.2.29 on 2026-03-18 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_alter_company_cover_image_alter_company_location_and_more'),
        ('Project', '0005_alter_banner_image_alter_banner_image_mobile'),
        ('authentication', '0007_alter_user_avatar'),
        ('job', '0013_jobpostactivity_ai_analysis_cons_and_more'),
        ('files', '0001_initial'),
        ('common', '0011_career_is_hot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='city',
        ),
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
        migrations.RemoveField(
            model_name='location',
            name='district',
        ),
        migrations.RemoveField(
            model_name='location',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='district',
        ),
        migrations.AlterField(
            model_name='career',
            name='icon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.file'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
