import { CVData, CVTemplateMeta } from '@/types/cvBuilder';

export const CV_TEMPLATES_CATALOG: CVTemplateMeta[] = [
  {
    id: 'modern-navy',
    name: 'Modern Navy',
    vietnameseName: 'Đảo Phú Quốc',
    description: 'Thiết kế 2 cột hiện đại, cân đối hài hòa giữa ảnh đại diện, kỹ năng và kinh nghiệm thực chiến.',
    category: 'modern',
    thumbnailUrl: '/assets/images/cv-templates/modern-navy.png',
    badge: 'Phổ biến nhất',
    defaultColors: ['#1e40af', '#0284c7', '#059669', '#7c3aed', '#dc2626', '#1e293b'],
    recommendedRole: 'Nhân viên kinh doanh, Marketing, Chuyên viên phân tích',
    isPopular: true,
  },
  {
    id: 'minimal-clean',
    name: 'Minimal Clean',
    vietnameseName: 'Đảo Nam Du',
    description: 'Bố cục 1 cột tối giản, tinh tế, tối ưu hóa 100% cho hệ thống quét tự động ATS của nhà tuyển dụng.',
    category: 'simple',
    thumbnailUrl: '/assets/images/cv-templates/minimal-clean.png',
    badge: 'Chuẩn ATS',
    defaultColors: ['#0f172a', '#2563eb', '#0d9488', '#4b5563', '#b45309'],
    recommendedRole: 'Kỹ sư phần mềm, Tài chính - Kế toán, Nhân sự',
    isPopular: true,
  },
  {
    id: 'executive-emerald',
    name: 'Executive Emerald',
    vietnameseName: 'Đảo Phú Quý',
    description: 'Phong cách lãnh đạo chuyên nghiệp với dải banner sang trọng, nhấn mạnh học vấn và thành tựu.',
    category: 'executive',
    thumbnailUrl: '/assets/images/cv-templates/executive-emerald.png',
    badge: 'Cấp Quản lý',
    defaultColors: ['#065f46', '#1e3a8a', '#831843', '#312e81', '#18181b'],
    recommendedRole: 'Giám đốc, Trưởng phòng, Quản lý dự án, Chuyên gia cao cấp',
  },
  {
    id: 'creative-coral',
    name: 'Creative Coral',
    vietnameseName: 'Đảo Bình Ba',
    description: 'Phối màu trẻ trung, năng động với thẻ kỹ năng bắt mắt, giúp ứng viên nổi bật trong mắt NTD sáng tạo.',
    category: 'creative',
    thumbnailUrl: '/assets/images/cv-templates/creative-coral.png',
    badge: 'Sáng tạo',
    defaultColors: ['#e11d48', '#f97316', '#8b5cf6', '#0ea5e9', '#10b981'],
    recommendedRole: 'UI/UX Designer, Content Creator, Graphic Design, Event Planner',
    isPopular: true,
  },
  {
    id: 'tech-dark',
    name: 'Tech & Developer',
    vietnameseName: 'Thung Lũng Silicon',
    description: 'Tối ưu dành riêng cho ngành Công nghệ thông tin: nổi bật Github, Tech Stack, Dự án mã nguồn.',
    category: 'tech',
    thumbnailUrl: '/assets/images/cv-templates/tech-dark.png',
    badge: 'Dành cho IT',
    defaultColors: ['#2563eb', '#10b981', '#6366f1', '#f59e0b', '#06b6d4', '#3b82f6'],
    recommendedRole: 'Frontend / Backend / Fullstack Developer, DevOps, Data Engineer',
  },
  {
    id: 'classic-serif',
    name: 'Classic Elegant',
    vietnameseName: 'Cố Đô Tràng An',
    description: 'Đậm chất báo chí & văn hóa thanh lịch, bố cục rõ ràng, trang trọng và đáng tin cậy tuyệt đối.',
    category: 'professional',
    thumbnailUrl: '/assets/images/cv-templates/classic-serif.png',
    defaultColors: ['#334155', '#1e293b', '#78350f', '#14532d', '#4c1d95'],
    recommendedRole: 'Giáo dục, Luật sư, Nghiên cứu viên, Biên phiên dịch',
  },
  {
    id: 'nordic-minimal',
    name: 'Nordic Minimal',
    vietnameseName: 'Bắc Âu Tối Giản',
    description: 'Đường nét tinh giản, typography phong cách Thụy Điển, tối ưu hóa cho Product Manager, UI/UX Designer và Tech Lead.',
    category: 'simple',
    thumbnailUrl: '/assets/images/cv-templates/nordic-minimal.png',
    badge: 'Mới ra mắt',
    defaultColors: ['#0f172a', '#334155', '#047857', '#4338ca', '#b45309'],
    recommendedRole: 'Product Manager, UI/UX Designer, Data Analyst, Tech Lead',
    isPopular: true,
  },
  {
    id: 'corporate-compact',
    name: 'Corporate Compact',
    vietnameseName: 'Doanh Nghiệp 1 Trang',
    description: 'Bố cục 1 trang cô đọng, tối ưu quét mắt trong 6 giây, phù hợp Tài chính, Ngân hàng, Big4, Kiểm toán & Logistics.',
    category: 'professional',
    thumbnailUrl: '/assets/images/cv-templates/corporate-compact.png',
    badge: 'Chuẩn 1 Trang',
    defaultColors: ['#1e293b', '#1e3a8a', '#065f46', '#831843', '#78350f'],
    recommendedRole: 'Tài chính, Ngân hàng, Big4, Kiểm toán, Kế toán, Logistics',
    isPopular: true,
  },
];

export const INITIAL_CV_SAMPLE_DATA: CVData = {
  title: 'CV - Ứng tuyển Chuyên viên',
  templateId: 'modern-navy',
  theme: {
    primaryColor: '#1e40af',
    fontFamily: 'Inter',
    fontSize: 'medium',
    spacing: 'normal',
    avatarShape: 'circle',
    showAvatar: true,
    paperSize: 'A4',
  },
  personalInfo: {
    fullName: 'NGUYỄN TRÚC QUỲNH MY',
    title: 'Chuyên viên Marketing & Truyền thông',
    email: 'quynhmy.nguyen@example.com',
    phoneNumber: '0912 345 678',
    address: 'Quận 1, TP. Hồ Chí Minh',
    dob: '15/08/1998',
    gender: 'Nữ',
    avatarUrl: '/images/cv-avatars/avatar-modern.jpg',
    website: 'quynhmy.portfolio.me',
    linkedin: 'linkedin.com/in/quynhmy-nguyen',
    github: '',
    bio: 'Chuyên viên Marketing với hơn 4 năm kinh nghiệm trong việc xây dựng chiến dịch Performance & Brand Awareness cho các doanh nghiệp TMĐT và Công nghệ. Có tư duy phân tích số liệu nhạy bén, quản trị ngân sách hiệu quả và luôn hướng tới việc nâng cao tỉ lệ chuyển đổi (ROI).',
  },
  experiences: [
    {
      id: 'exp-1',
      position: 'Senior Marketing Executive',
      company: 'Công ty Cổ phần Công nghệ ABC',
      startDate: '03/2022',
      endDate: 'Hiện tại',
      isCurrent: true,
      description:
        '• Hoạch định và thực thi các chiến dịch Digital Marketing đa kênh (Google Ads, Meta Ads, TikTok), quản lý ngân sách 200M+/tháng.\n• Tăng trưởng lượng truy cập tự nhiên (Organic Traffic) lên 45% và tỉ lệ chuyển đổi khách hàng tiềm năng tăng 28% sau 6 tháng.\n• Phối hợp chặt chẽ cùng đội ngũ Design và Content để sản xuất các ấn phẩm truyền thông chất lượng cao.',
    },
    {
      id: 'exp-2',
      position: 'Digital Marketing Specialist',
      company: 'Tập đoàn Bán lẻ XYZ',
      startDate: '06/2020',
      endDate: '02/2022',
      isCurrent: false,
      description:
        '• Xây dựng và quản lý các kênh Social Media đạt mốc 150K followers với chỉ số tương tác (ER) đạt trung bình 6.8%.\n• Lập kế hoạch Email Marketing tự động hóa qua HubSpot, nâng tỷ lệ mở mail (Open Rate) đạt 32%.\n• Theo dõi và phân tích báo cáo hiệu suất hàng tuần bằng Google Analytics và Looker Studio.',
    },
  ],
  educations: [
    {
      id: 'edu-1',
      school: 'Đại học Kinh Tế TP. Hồ Chí Minh (UEH)',
      major: 'Quản trị Marketing',
      degree: 'Cử nhân Giỏi',
      startDate: '2016',
      endDate: '2020',
      gpa: '3.6/4.0',
      description: 'Đạt học bổng Khuyến khích học tập 3 kỳ liên tiếp. Trưởng ban đối ngoại CLB Marketing UEH.',
    },
  ],
  skills: [
    { id: 'sk-1', name: 'Digital Advertising (Meta/Google)', level: 5 },
    { id: 'sk-2', name: 'Content & Copywriting', level: 5 },
    { id: 'sk-3', name: 'Data Analysis (GA4, Looker Studio)', level: 4 },
    { id: 'sk-4', name: 'SEO & Performance Optimization', level: 4 },
    { id: 'sk-5', name: 'Kỹ năng thuyết trình & Đàm phán', level: 5 },
    { id: 'sk-6', name: 'Làm việc nhóm & Quản lý dự án', level: 4 },
  ],
  languages: [
    { id: 'lang-1', name: 'Tiếng Việt', proficiency: 'Bản ngữ' },
    { id: 'lang-2', name: 'Tiếng Anh', proficiency: 'IELTS 7.5' },
  ],
  certificates: [
    {
      id: 'cert-1',
      name: 'Google Ads Search & Measurement Certification',
      organization: 'Google Skillshop',
      issueDate: '2023',
    },
    {
      id: 'cert-2',
      name: 'Inbound Marketing Certified',
      organization: 'HubSpot Academy',
      issueDate: '2022',
    },
  ],
  projects: [
    {
      id: 'proj-1',
      name: 'Chiến dịch Ra mắt Ứng dụng SuperApp 2023',
      role: 'Lead Project Marketing',
      startDate: '01/2023',
      endDate: '06/2023',
      technologies: 'Omnichannel, Influencer Marketing, PR',
      description:
        'Chiến dịch thu hút 100.000 lượt tải app trong 30 ngày đầu tiên, lọt top 3 ứng dụng phổ biến trên App Store & Google Play.',
    },
  ],
};

// Rich template-specific sample datasets with diverse authentic headshot portraits
export const TEMPLATE_SAMPLE_DATA_MAP: Record<string, Partial<CVData>> = {
  'modern-navy': {
    personalInfo: {
      fullName: 'NGUYỄN TRÚC QUỲNH MY',
      title: 'Chuyên viên Marketing & Truyền thông',
      email: 'quynhmy.nguyen@example.com',
      phoneNumber: '0912 345 678',
      address: 'Quận 1, TP. Hồ Chí Minh',
      dob: '15/08/1998',
      gender: 'Nữ',
      avatarUrl: '/images/cv-avatars/avatar-modern.jpg',
      website: 'quynhmy.portfolio.me',
      linkedin: 'linkedin.com/in/quynhmy-nguyen',
      bio: 'Chuyên viên Marketing với hơn 4 năm kinh nghiệm trong việc xây dựng chiến dịch Performance & Brand Awareness cho các doanh nghiệp TMĐT và Công nghệ. Tư duy phân tích số liệu nhạy bén và quản trị ngân sách hiệu quả.',
    },
  },
  'minimal-clean': {
    personalInfo: {
      fullName: 'TRẦN HOÀNG NAM',
      title: 'Chuyên viên Tài chính & Kiểm toán',
      email: 'hoangnam.tran@example.com',
      phoneNumber: '0938 123 456',
      address: 'Cầu Giấy, Hà Nội',
      dob: '22/04/1996',
      gender: 'Nam',
      avatarUrl: '/images/cv-avatars/avatar-minimal.jpg',
      website: 'hoangnam-finance.com',
      linkedin: 'linkedin.com/in/hoangnam-tran',
      bio: 'Chuyên viên Tài chính với hơn 5 năm kinh nghiệm phân tích báo cáo tài chính, thẩm định dự án đầu tư và tối ưu hóa chi phí vận hành cho các tập đoàn đa quốc gia. Chứng chỉ CFA Level 2.',
    },
  },
  'executive-emerald': {
    personalInfo: {
      fullName: 'LÊ ĐỨC MINH',
      title: 'Giám đốc Vận hành & Dự án (COO)',
      email: 'ducminh.le@example.com',
      phoneNumber: '0903 888 999',
      address: 'Quận 7, TP. Hồ Chí Minh',
      dob: '10/11/1988',
      gender: 'Nam',
      avatarUrl: '/images/cv-avatars/avatar-executive.jpg',
      website: 'ducminh.lead.vn',
      linkedin: 'linkedin.com/in/ducminh-le-coo',
      bio: 'Hơn 10 năm kinh nghiệm lãnh đạo và vận hành chuỗi cung ứng, mở rộng quy mô kinh doanh từ 50 lên 500 nhân sự. Kỹ năng quản trị chiến lược, chuyển đổi số và nâng cao biên lợi nhuận doanh nghiệp.',
    },
  },
  'creative-coral': {
    personalInfo: {
      fullName: 'VŨ THẢO LINH',
      title: 'Senior UI/UX & Brand Designer',
      email: 'thaolinh.design@example.com',
      phoneNumber: '0977 654 321',
      address: 'Bình Thạnh, TP. Hồ Chí Minh',
      dob: '05/09/1999',
      gender: 'Nữ',
      avatarUrl: '/images/cv-avatars/avatar-creative.jpg',
      website: 'behance.net/thaolinhart',
      linkedin: 'linkedin.com/in/thaolinh-uiux',
      bio: 'Nhà thiết kế sản phẩm kỹ thuật số với đam mê tạo ra trải nghiệm người dùng trực quan, thẩm mỹ cao và tăng trưởng chuyển đổi cho các sản phẩm Fintech, E-commerce và SaaS.',
    },
  },
  'tech-dark': {
    personalInfo: {
      fullName: 'ĐỖ MINH TUẤN',
      title: 'Senior Fullstack Software Engineer',
      email: 'minhtuan.dev@example.com',
      phoneNumber: '0982 999 111',
      address: 'Thanh Xuân, Hà Nội',
      dob: '19/03/1995',
      gender: 'Nam',
      avatarUrl: '/images/cv-avatars/avatar-tech.jpg',
      website: 'minhtuan.tech',
      linkedin: 'linkedin.com/in/minhtuan-se',
      github: 'github.com/minhtuan-dev',
      bio: 'Kỹ sư phần mềm 6+ năm kinh nghiệm xây dựng hệ thống phân tán microservices (Golang, Node.js, React/Next.js) phục vụ hơn 2 triệu người dùng thực tế. Đam mê mã nguồn mở và kiến trúc đám mây AWS.',
    },
  },
  'classic-serif': {
    personalInfo: {
      fullName: 'PHAN THỊ NGỌC ANH',
      title: 'Chuyên viên Pháp chế & Quản trị Nhân sự',
      email: 'ngocanh.phan@example.com',
      phoneNumber: '0918 333 444',
      address: 'Ba Đình, Hà Nội',
      dob: '12/12/1992',
      gender: 'Nữ',
      avatarUrl: '/images/cv-avatars/avatar-classic.jpg',
      website: 'ngocanh-legal.vn',
      linkedin: 'linkedin.com/in/ngocanh-phan-hr',
      bio: 'Chuyên gia pháp chế doanh nghiệp với hơn 7 năm tư vấn luật thương mại, hợp đồng đầu tư và xây dựng chính sách nhân sự cho các tập đoàn FDI tại Việt Nam.',
    },
  },
  'nordic-minimal': {
    personalInfo: {
      fullName: 'BÙI QUỐC HUY',
      title: 'Lead Product Manager',
      email: 'quochuy.pm@example.com',
      phoneNumber: '0909 555 777',
      address: 'Quận 2, TP. Thủ Đức',
      dob: '28/06/1994',
      gender: 'Nam',
      avatarUrl: '/images/cv-avatars/avatar-nordic.jpg',
      website: 'quochuy.io',
      linkedin: 'linkedin.com/in/quochuy-pm',
      bio: 'Product Manager dẫn dắt phát triển sản phẩm B2B SaaS từ giai đoạn MVP đến khi đạt 50.000 người dùng trả phí. Định hướng theo dữ liệu (Data-driven) và phương pháp Agile/Scrum linh hoạt.',
    },
  },
  'corporate-compact': {
    personalInfo: {
      fullName: 'HOÀNG THU TRANG',
      title: 'Chuyên viên Phân tích Đầu tư & Ngân hàng',
      email: 'thutrang.hoang@example.com',
      phoneNumber: '0934 777 888',
      address: 'Quận 3, TP. Hồ Chí Minh',
      dob: '14/02/1997',
      gender: 'Nữ',
      avatarUrl: '/images/cv-avatars/avatar-corporate.jpg',
      website: 'thutrang-finance.me',
      linkedin: 'linkedin.com/in/thutrang-hoang',
      bio: 'Chuyên viên phân tích đầu tư với kinh nghiệm định giá doanh nghiệp, thẩm định M&A và quản lý danh mục tài sản tại công ty chứng khoán Top 5 Việt Nam.',
    },
  },
};

export function createEmptyCVData(templateCode: string, primaryColor?: string): CVData {
  const templateMeta =
    CV_TEMPLATES_CATALOG.find((t) => t.id === templateCode) || CV_TEMPLATES_CATALOG[0];
  return {
    title: 'CV Ứng tuyển',
    templateId: templateMeta.id,
    theme: {
      primaryColor: primaryColor || templateMeta.defaultColors[0] || '#1e40af',
      fontFamily: 'Inter',
      fontSize: 'medium',
      spacing: 'normal',
      avatarShape: 'circle',
      showAvatar: true,
      paperSize: 'A4',
    },
    personalInfo: {
      fullName: '',
      title: '',
      email: '',
      phoneNumber: '',
      address: '',
      dob: '',
      gender: '',
      avatarUrl: '',
      website: '',
      linkedin: '',
      github: '',
      bio: '',
    },
    experiences: [],
    educations: [],
    skills: [],
    languages: [],
    certificates: [],
    projects: [],
  };
}

export function getSampleDataForTemplate(templateCode: string): CVData {
  const specificSample = TEMPLATE_SAMPLE_DATA_MAP[templateCode] || {};
  return {
    ...INITIAL_CV_SAMPLE_DATA,
    templateId: templateCode,
    ...specificSample,
    personalInfo: {
      ...INITIAL_CV_SAMPLE_DATA.personalInfo,
      ...(specificSample.personalInfo || {}),
    },
  };
}

