# Generated by Django 4.2.29 on 2026-03-19 03:23

import autoslug.fields
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('job_name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=300, populate_from='job_name', slugify=django.utils.text.slugify, unique_with=['id'])),
                ('deadline', models.DateField(db_index=True)),
                ('quantity', models.IntegerField()),
                ('gender_required', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('job_description', ckeditor.fields.RichTextField()),
                ('job_requirement', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('benefits_enjoyed', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('position', models.SmallIntegerField(choices=[(1, 'Senior Management'), (2, 'Middle Management'), (3, 'Team Leader - Supervisor'), (4, 'Specialist'), (5, 'Staff / Employee'), (6, 'Collaborator')])),
                ('type_of_workplace', models.SmallIntegerField(choices=[(1, 'Office-based'), (2, 'Hybrid'), (3, 'Remote / Work from home')])),
                ('experience', models.SmallIntegerField(choices=[(1, 'No experience'), (2, 'Under 1 year'), (3, '1 year'), (4, '2 years'), (5, '3 years'), (6, '4 years'), (7, '5 years'), (8, 'Over 5 years')])),
                ('academic_level', models.SmallIntegerField(choices=[(1, 'Postgraduate'), (2, 'University'), (3, 'College'), (4, 'Vocational / Intermediate'), (5, 'High School'), (6, 'Certificate')])),
                ('job_type', models.SmallIntegerField(choices=[(1, 'Full-time Permanent'), (2, 'Full-time Temporary'), (3, 'Part-time Permanent'), (4, 'Part-time Temporary'), (5, 'Consultancy Contract'), (6, 'Internship'), (7, 'Other')])),
                ('salary_min', models.IntegerField()),
                ('salary_max', models.IntegerField()),
                ('is_hot', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Rejected'), (3, 'Approved')], db_index=True, default=1)),
                ('contact_person_name', models.CharField(max_length=100)),
                ('contact_person_phone', models.CharField(max_length=15)),
                ('contact_person_email', models.EmailField(max_length=100)),
                ('views', models.BigIntegerField(default=0)),
                ('shares', models.BigIntegerField(default=0)),
                ('career', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts', to='common.career')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='info.company')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts', to='locations.location')),
            ],
            options={
                'db_table': 'project_job_job_post',
            },
        ),
        migrations.CreateModel(
            name='SavedJobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Saved job posts',
                'db_table': 'project_job_saved_job_post',
            },
        ),
        migrations.CreateModel(
            name='JobPostNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('job_name', models.CharField(max_length=255)),
                ('position', models.SmallIntegerField(choices=[(1, 'Senior Management'), (2, 'Middle Management'), (3, 'Team Leader - Supervisor'), (4, 'Specialist'), (5, 'Staff / Employee'), (6, 'Collaborator')], null=True)),
                ('experience', models.SmallIntegerField(choices=[(1, 'No experience'), (2, 'Under 1 year'), (3, '1 year'), (4, '2 years'), (5, '3 years'), (6, '4 years'), (7, '5 years'), (8, 'Over 5 years')], null=True)),
                ('salary', models.IntegerField(null=True)),
                ('frequency', models.IntegerField(choices=[(1, 'Daily'), (2, 'Every 3 Days'), (3, 'Weekly')])),
                ('is_active', models.BooleanField(default=False)),
                ('career', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_post_notifications', to='common.career')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_post_notifications', to='locations.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Job post notifications',
                'db_table': 'project_job_job_post_notification',
            },
        ),
        migrations.CreateModel(
            name='JobPostActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending Confirmation'), (2, 'Contacted'), (3, 'Tested'), (4, 'Interviewed'), (5, 'Hired'), (6, 'Not Selected')], db_index=True, default=1)),
                ('is_sent_email', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('ai_analysis_score', models.IntegerField(blank=True, null=True)),
                ('ai_analysis_summary', models.TextField(blank=True, null=True)),
                ('ai_analysis_skills', models.TextField(blank=True, null=True)),
                ('ai_analysis_pros', models.TextField(blank=True, null=True)),
                ('ai_analysis_cons', models.TextField(blank=True, null=True)),
                ('ai_analysis_matching_skills', models.JSONField(blank=True, null=True)),
                ('ai_analysis_missing_skills', models.JSONField(blank=True, null=True)),
                ('ai_analysis_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobpost')),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Job posts activity',
                'db_table': 'project_job_job_post_activity',
            },
        ),
        migrations.AddField(
            model_name='jobpost',
            name='peoples_applied',
            field=models.ManyToManyField(related_name='job_posts_activity', through='job.JobPostActivity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='peoples_saved',
            field=models.ManyToManyField(related_name='saved_job_posts', through='job.SavedJobPost', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='jobpostactivity',
            index=models.Index(fields=['status', 'is_deleted'], name='job_act_stt_del_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpostactivity',
            index=models.Index(fields=['job_post', 'status'], name='job_act_post_stt_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpostactivity',
            index=models.Index(fields=['create_at'], name='job_act_create_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['status', 'deadline'], name='job_post_stt_dead_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['status', 'create_at'], name='job_post_stt_create_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['deadline', 'create_at'], name='job_post_dead_create_idx'),
        ),
    ]
