# Generated by Django 4.2.29 on 2026-03-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['status', 'deadline', '-update_at', '-create_at'], name='job_post_list_idx'),
        ),
    ]
