# Generated by Django 4.2.29 on 2026-03-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobpost_job_post_list_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostactivity',
            name='ai_analysis_progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
