# Generated by Django 4.2 on 2026-04-15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
        ('job', '0003_jobpostactivity_ai_analysis_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='interview_template',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='linked_job_posts',
                to='interview.questiongroup',
            ),
        ),
    ]
