# Generated by Django 4.2 on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0004_jobpost_interview_template"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="jobpostactivity",
            constraint=models.UniqueConstraint(
                fields=("user", "job_post", "is_deleted"),
                name="uq_jobpostactivity_user_jobpost_deleted_state",
            ),
        ),
    ]
