# Generated by Django 4.2.30 on 2026-08-24 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_alter_resume_type_resume_idx_resume_active_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0011_jobpost_auto_sourcing_pipeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostactivity',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.resume'),
        ),
        migrations.CreateModel(
            name='JobOfferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('position_title', models.CharField(max_length=255, verbose_name='Vị trí bổ nhiệm')),
                ('salary_offered', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Mức lương đề xuất')),
                ('allowance', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Phụ cấp')),
                ('start_date', models.DateField(verbose_name='Ngày nhận việc dự kiến')),
                ('expiration_date', models.DateField(verbose_name='Hạn phản hồi')),
                ('work_location', models.CharField(blank=True, default='', max_length=255, verbose_name='Địa điểm làm việc')),
                ('benefits_note', models.TextField(blank=True, default='', verbose_name='Quyền lợi & Đãi ngộ')),
                ('terms_and_conditions', models.TextField(blank=True, default='', verbose_name='Điều khoản công việc')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('sent', 'Đã gửi tới ứng viên'), ('accepted', 'Ứng viên đã chấp nhận'), ('declined', 'Ứng viên từ chối'), ('expired', 'Đã hết hạn')], db_index=True, default='draft', max_length=20)),
                ('candidate_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm ứng viên ký/xác nhận')),
                ('candidate_feedback', models.TextField(blank=True, default='', verbose_name='Phản hồi từ ứng viên')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer_letter', to='job.jobpostactivity', verbose_name='Đơn ứng tuyển')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_offer_letters', to=settings.AUTH_USER_MODEL, verbose_name='Ứng viên')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_letters', to='info.company', verbose_name='Công ty')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_offers', to=settings.AUTH_USER_MODEL)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_letters', to='job.jobpost', verbose_name='Tin tuyển dụng')),
            ],
            options={
                'verbose_name': 'Job Offer Letter',
                'verbose_name_plural': 'Job Offer Letters',
                'db_table': 'project_job_offer_letter',
                'ordering': ['-create_at'],
            },
        ),
    ]
