# Generated by Django 4.2.29 on 2026-03-18 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('job', '0012_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostactivity',
            name='ai_analysis_cons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpostactivity',
            name='ai_analysis_matching_skills',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpostactivity',
            name='ai_analysis_missing_skills',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpostactivity',
            name='ai_analysis_pros',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='jobpostnotification',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_post_notifications', to='locations.city'),
        ),
    ]
