# Generated by Django 4.2.30 on 2026-09-22 09:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_alter_jobpostactivity_resume_jobofferletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostDailyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Ngày thống kê')),
                ('views', models.PositiveIntegerField(default=1, verbose_name='Số lượt xem')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_views', to='job.jobpost', verbose_name='Tin tuyển dụng')),
            ],
            options={
                'verbose_name': 'Lượt xem tin tuyển dụng theo ngày',
                'verbose_name_plural': 'Lượt xem tin tuyển dụng theo ngày',
                'db_table': 'project_job_post_daily_view',
                'indexes': [models.Index(fields=['date'], name='project_job_date_d716f8_idx'), models.Index(fields=['job_post', 'date'], name='project_job_job_pos_c86a92_idx')],
                'unique_together': {('job_post', 'date')},
            },
        ),
    ]
