# Generated by Django 4.2.30 on 2026-09-22 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0010_interviewscript_interviewsession_interview_script'),
        ('job', '0013_jobpostdailyview'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='interview_script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_job_posts', to='interview.interviewscript', verbose_name='Kịch bản phỏng vấn AI'),
        ),
    ]
