# Generated by Django 4.2.30 on 2026-09-17 04:13

import apps.operations.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0013_company_evaluation_weights'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncOperation',
            fields=[
                ('id', models.CharField(default=apps.operations.models.generate_operation_id, max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Đang trong hàng đợi'), ('running', 'Đang xử lý'), ('completed', 'Hoàn tất'), ('failed', 'Thất bại'), ('cancelled', 'Đã hủy')], db_index=True, default='queued', max_length=32)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('current_step_key', models.CharField(blank=True, max_length=64)),
                ('steps', models.JSONField(default=list)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('timeout_seconds', models.PositiveIntegerField(default=600)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='async_operations', to='info.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='async_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='operations__user_id_ed1d87_idx'), models.Index(fields=['company', 'status'], name='operations__company_8b8bcd_idx'), models.Index(fields=['type', 'status'], name='operations__type_b25fad_idx')],
            },
        ),
    ]
