# Generated by Django 4.2.29 on 2026-03-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_add_candidate_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employee_size',
            field=models.SmallIntegerField(choices=[(1, 'Under 10 employees'), (2, '10 - 150 employees'), (3, '150 - 300 employees'), (4, 'Over 300 employees')], null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married')], default='S', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='languageskill',
            name='language',
            field=models.SmallIntegerField(choices=[(1, 'Vietnamese'), (2, 'English'), (3, 'Japanese'), (4, 'French'), (5, 'Chinese'), (6, 'Russian'), (7, 'Korean'), (8, 'German'), (9, 'Italian'), (10, 'Arabic'), (11, 'Other')]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='academic_level',
            field=models.SmallIntegerField(choices=[(1, 'Postgraduate'), (2, 'University'), (3, 'College'), (4, 'Vocational / Intermediate'), (5, 'High School'), (6, 'Certificate')], null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.SmallIntegerField(choices=[(1, 'No experience'), (2, 'Under 1 year'), (3, '1 year'), (4, '2 years'), (5, '3 years'), (6, '4 years'), (7, '5 years'), (8, 'Over 5 years')], null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_type',
            field=models.SmallIntegerField(choices=[(1, 'Full-time Permanent'), (2, 'Full-time Temporary'), (3, 'Part-time Permanent'), (4, 'Part-time Temporary'), (5, 'Consultancy Contract'), (6, 'Internship'), (7, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='position',
            field=models.SmallIntegerField(choices=[(1, 'Senior Management'), (2, 'Middle Management'), (3, 'Team Leader - Supervisor'), (4, 'Specialist'), (5, 'Staff / Employee'), (6, 'Collaborator')], null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='type_of_workplace',
            field=models.SmallIntegerField(choices=[(1, 'Office-based'), (2, 'Hybrid'), (3, 'Remote / Work from home')], null=True),
        ),
    ]
