# Generated by Django 4.2.30 on 2026-05-17 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0008_jobpostactivity_ai_review_metadata'),
        ('info', '0005_resume_interaction_uniques'),
        ('interview', '0002_questiongroup_evaluation_rubric'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('language', models.CharField(default='vi', max_length=16)),
                ('voice_type', models.CharField(choices=[('cloned', 'Cloned'), ('preset', 'Preset')], default='cloned', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('ready', 'Ready'), ('disabled', 'Disabled'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20)),
                ('preset_engine', models.CharField(blank=True, default='vieneu', max_length=80)),
                ('preset_voice_id', models.CharField(blank=True, default='', max_length=255)),
                ('consent_confirmed', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_voice_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_interview_voice_profile',
                'ordering': ['name', '-create_at'],
            },
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='voice_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to='interview.voiceprofile', verbose_name='Voice profile'),
        ),
        migrations.CreateModel(
            name='VoiceProfileSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('reference_text', models.TextField()),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('audio_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_profile_samples', to='files.file')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_voice_profile_samples', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='interview.voiceprofile')),
            ],
            options={
                'db_table': 'project_interview_voice_profile_sample',
                'ordering': ['sort_order', 'create_at', 'id'],
                'indexes': [models.Index(fields=['profile', 'sort_order'], name='idx_voice_sample_profile_order')],
            },
        ),
        migrations.CreateModel(
            name='VoiceProfileGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_profile_grants', to='info.company')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_voice_profiles', to=settings.AUTH_USER_MODEL)),
                ('job_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_profile_grants', to='job.jobpost')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='interview.voiceprofile')),
            ],
            options={
                'db_table': 'project_interview_voice_profile_grant',
                'ordering': ['-is_default', '-create_at'],
                'indexes': [models.Index(fields=['company', 'is_active', 'is_default'], name='idx_voice_grant_company'), models.Index(fields=['job_post', 'is_active', 'is_default'], name='idx_voice_grant_job'), models.Index(fields=['profile', 'is_active'], name='idx_voice_grant_profile_active')],
            },
        ),
        migrations.AddIndex(
            model_name='voiceprofile',
            index=models.Index(fields=['status', 'voice_type'], name='idx_voice_profile_status_type'),
        ),
        migrations.AddIndex(
            model_name='voiceprofile',
            index=models.Index(fields=['created_by', 'status'], name='idx_voice_prof_creator_st'),
        ),
    ]
