# Generated by Django 4.2.30 on 2026-08-24 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_voiceprofile_interviewsession_voice_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='timeline_highlights',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Mốc thời gian nổi bật'),
        ),
        migrations.CreateModel(
            name='InterviewProctoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('tab_switch', 'Chuyển tab'), ('no_face_detected', 'Mất nhận diện khuôn mặt'), ('multiple_faces_detected', 'Phát hiện nhiều khuôn mặt'), ('audio_anomaly', 'Âm thanh bất thường')], max_length=40, verbose_name='Loại vi phạm')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm ghi nhận')),
                ('duration_seconds', models.FloatField(default=0.0, verbose_name='Thời lượng (giây)')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Dữ liệu chi tiết')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_events', to='interview.interviewsession', verbose_name='Buổi phỏng vấn')),
            ],
            options={
                'verbose_name': 'Proctoring Event',
                'verbose_name_plural': 'Proctoring Events',
                'db_table': 'project_interview_proctoring_event',
                'ordering': ['-timestamp'],
            },
        ),
    ]
