# Generated by Django 4.2.29 on 2026-03-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_question_company_questiongroup_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='question_cursor',
            field=models.IntegerField(default=0, verbose_name='Chỉ số câu hỏi hiện tại'),
        ),
    ]
