# Generated by Django 4.2.30 on 2026-09-10 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_auditlog_action'),
        ('interview', '0004_interviewsession_timeline_highlights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='session_metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='Metadata phiên phỏng vấn / Gợi ý AI'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='session_type',
            field=models.CharField(choices=[('official', 'Phỏng vấn ứng tuyển'), ('mock', 'Phỏng vấn thử')], db_index=True, default='official', max_length=20, verbose_name='Phân loại phiên phỏng vấn'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='time_limit_per_question',
            field=models.IntegerField(default=120, verbose_name='Thời gian trả lời mỗi câu (giây)'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_structure',
            field=models.JSONField(blank=True, null=True, verbose_name='Cấu trúc gợi ý trả lời'),
        ),
        migrations.AddField(
            model_name='question',
            name='default_duration_seconds',
            field=models.IntegerField(default=120, verbose_name='Thời gian trả lời (giây)'),
        ),
        migrations.AddField(
            model_name='question',
            name='follow_up_questions',
            field=models.JSONField(blank=True, null=True, verbose_name='Câu hỏi nối tiếp có thể gặp'),
        ),
        migrations.AddField(
            model_name='question',
            name='important_tips',
            field=models.JSONField(blank=True, null=True, verbose_name='Mẹo quan trọng cho ứng viên'),
        ),
        migrations.AddField(
            model_name='question',
            name='interviewer_intent',
            field=models.TextField(blank=True, default='', verbose_name='Mục đích phỏng vấn / Ý đồ đánh giá'),
        ),
        migrations.CreateModel(
            name='SalaryBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('position_title', models.CharField(db_index=True, max_length=255, verbose_name='Tên vị trí / Chức danh')),
                ('experience_level', models.CharField(choices=[('entry', 'Mới ra trường / Dưới 1 năm'), ('junior', '1 - 2 năm'), ('mid', '2 - 4 năm'), ('senior', '4 - 7 năm'), ('lead', 'Trưởng nhóm / Manager / Chuyên gia')], db_index=True, default='junior', max_length=30, verbose_name='Cấp bậc kinh nghiệm')),
                ('salary_min', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Mức lương tối thiểu (VND)')),
                ('salary_max', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Mức lương tối đa (VND)')),
                ('salary_avg', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=14, null=True, verbose_name='Mức lương trung bình (VND)')),
                ('year', models.IntegerField(db_index=True, default=2026, verbose_name='Năm khảo sát')),
                ('sample_count', models.IntegerField(default=100, verbose_name='Số lượng mẫu khảo sát')),
                ('is_hot', models.BooleanField(default=False, verbose_name='Vị trí tuyển dụng hot')),
                ('career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_benchmarks', to='common.career', verbose_name='Ngành nghề')),
            ],
            options={
                'verbose_name': 'Salary Benchmark',
                'verbose_name_plural': 'Salary Benchmarks',
                'db_table': 'project_interview_salary_benchmark',
                'ordering': ['-is_hot', 'position_title', 'salary_min'],
                'indexes': [models.Index(fields=['career', 'experience_level'], name='idx_salary_career_exp'), models.Index(fields=['position_title', 'year'], name='idx_salary_pos_year')],
            },
        ),
    ]
