# Generated by Django 4.2.30 on 2026-09-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_interviewsession_session_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tiêu đề / Chủ đề ngắn'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('culture_fit', 'Phù hợp văn hóa'), ('general', 'Chung / Văn hóa'), ('technical', 'Kỹ năng chuyên môn'), ('behavioral', 'Hành vi'), ('situational', 'Xử lý tình huống'), ('problem_solving', 'Giải quyết vấn đề'), ('soft_skills', 'Kỹ năng mềm')], default='general', max_length=30, verbose_name='Danh mục'),
        ),
    ]
