# Generated by Django 4.2.29 on 2026-03-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_alter_interviewsession_question_cursor'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='ai_detailed_feedback',
            field=models.JSONField(blank=True, null=True, verbose_name='Phân tích chi tiết (AI)'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Thời gian dự kiến'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='status',
            field=models.CharField(choices=[('draft', 'Bản nháp'), ('scheduled', 'Đã lên lịch'), ('calibration', 'Kiểm tra thiết bị'), ('in_progress', 'Đang phỏng vấn'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy'), ('interrupted', 'Bị gián đoạn'), ('processing', 'Đang xử lý')], db_index=True, default='draft', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
