# Generated by Django 4.2.30 on 2026-09-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_questiongroup_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['sort_order', 'create_at', 'id'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='evaluation_rubric',
            field=models.JSONField(blank=True, null=True, verbose_name='Tiêu chí đánh giá Rubric'),
        ),
    ]
