# Generated by Django 4.2.30 on 2026-09-13 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0008_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='interview_language',
            field=models.CharField(choices=[('vi', 'Tiếng Việt'), ('en', 'Tiếng Anh'), ('ja', 'Tiếng Nhật'), ('ko', 'Tiếng Hàn')], db_index=True, default='vi', max_length=10, verbose_name='Ngôn ngữ phỏng vấn'),
        ),
        migrations.AlterField(
            model_name='interviewproctoringevent',
            name='duration_seconds',
            field=models.FloatField(default=0.0, verbose_name='Thời lượng tính bằng giây'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='ai_detailed_feedback',
            field=models.JSONField(blank=True, null=True, verbose_name='Phân tích chi tiết AI'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='ai_strengths',
            field=models.JSONField(blank=True, null=True, verbose_name='Điểm mạnh AI'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='ai_weaknesses',
            field=models.JSONField(blank=True, null=True, verbose_name='Điểm yếu AI'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interviews', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo Nhà tuyển dụng'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Thời lượng tính bằng giây'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='room_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Tên phòng LiveKit Room'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='time_limit_per_question',
            field=models.IntegerField(default=120, verbose_name='Thời gian trả lời mỗi câu tính bằng giây'),
        ),
        migrations.AlterField(
            model_name='interviewtranscript',
            name='speech_duration_ms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Thời lượng nói tính bằng mili giây'),
        ),
        migrations.AlterField(
            model_name='question',
            name='default_duration_seconds',
            field=models.IntegerField(default=120, verbose_name='Thời gian trả lời tính bằng giây'),
        ),
        migrations.AlterField(
            model_name='salarybenchmark',
            name='salary_avg',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=14, null=True, verbose_name='Mức lương trung bình VND'),
        ),
        migrations.AlterField(
            model_name='salarybenchmark',
            name='salary_max',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Mức lương tối đa VND'),
        ),
        migrations.AlterField(
            model_name='salarybenchmark',
            name='salary_min',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Mức lương tối thiểu VND'),
        ),
    ]
