# Generated by Django 4.2.30 on 2026-09-22 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0014_jobseekerprofile_cover_image'),
        ('interview', '0009_interviewsession_interview_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Tên kịch bản')),
                ('slug', models.CharField(blank=True, default='', max_length=255, verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='Mô tả mục tiêu')),
                ('scenario_type', models.CharField(choices=[('technical', 'Kỹ thuật chuyên môn'), ('behavioral', 'Hành vi & Văn hóa (STAR)'), ('sales', 'Kinh doanh & CSKH'), ('fresher', 'Fresher / Thực tập sinh'), ('leadership', 'Lãnh đạo & Quản lý'), ('situational', 'Xử lý tình huống'), ('custom', 'Tùy chỉnh riêng')], db_index=True, default='technical', max_length=32, verbose_name='Loại kịch bản')),
                ('hr_persona', models.CharField(choices=[('friendly', 'Thân thiện & Khích lệ'), ('professional', 'Chuyên nghiệp & Chuẩn mực STAR'), ('challenger', 'Thử thách & Đào sâu kỹ thuật')], default='professional', max_length=32, verbose_name='Phong thái HR')),
                ('system_prompt', models.TextField(blank=True, default='', verbose_name='Chỉ dẫn AI chuyên sâu')),
                ('greeting_message', models.TextField(blank=True, default='', verbose_name='Lời chào mở đầu')),
                ('closing_message', models.TextField(blank=True, default='', verbose_name='Lời cảm ơn kết thúc')),
                ('time_limit_per_question', models.IntegerField(default=120, verbose_name='Thời gian trả lời mỗi câu (giây)')),
                ('allow_ai_followup', models.BooleanField(default=True, verbose_name='Cho phép AI hỏi đào sâu')),
                ('max_followup_questions', models.IntegerField(default=2, verbose_name='Số câu hỏi phụ tối đa')),
                ('character_id', models.CharField(default='ng_c_linh', max_length=64, verbose_name='Mã nhân vật ảo')),
                ('voice_name', models.CharField(default='Trúc Ly', max_length=64, verbose_name='Tên giọng đọc TTS')),
                ('voice_speed', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Tốc độ giọng đọc')),
                ('evaluation_rubric', models.JSONField(blank=True, null=True, verbose_name='Tiêu chuẩn chấm điểm Rubric')),
                ('is_system_preset', models.BooleanField(db_index=True, default=False, verbose_name='Mẫu hệ thống')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Đang kích hoạt')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interview_scripts', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_scripts', to='info.company', verbose_name='Thuộc công ty')),
                ('question_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_scripts', to='interview.questiongroup', verbose_name='Bộ câu hỏi mặc định')),
                ('questions', models.ManyToManyField(blank=True, related_name='interview_scripts', to='interview.question', verbose_name='Danh sách câu hỏi')),
            ],
            options={
                'verbose_name': 'Interview Script',
                'verbose_name_plural': 'Interview Scripts',
                'db_table': 'project_interview_script',
                'ordering': ['-create_at'],
            },
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='interview_script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to='interview.interviewscript', verbose_name='Kịch bản phỏng vấn'),
        ),
    ]
