# Generated by Django 4.2.30 on 2026-10-01 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0010_interviewscript_interviewsession_interview_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewproctoringevent',
            name='event_type',
            field=models.CharField(choices=[('tab_switch', 'Cảnh báo chuyển tab'), ('tab_hidden', 'Rời khỏi tab'), ('tab_returned', 'Quay lại tab'), ('no_face_detected', 'Mất nhận diện khuôn mặt'), ('multiple_faces_detected', 'Phát hiện nhiều khuôn mặt'), ('audio_anomaly', 'Âm thanh bất thường')], max_length=40, verbose_name='Loại vi phạm'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='room_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Tên phòng phỏng vấn trực tuyến'),
        ),
        migrations.CreateModel(
            name='InterviewConnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('participant_identity', models.CharField(blank=True, default='', max_length=255, verbose_name='Định danh người tham gia')),
                ('participant_role', models.CharField(choices=[('candidate', 'Ứng viên'), ('employer', 'Nhà tuyển dụng'), ('agent', 'AI Agent'), ('observer', 'Người quan sát')], default='candidate', max_length=50, verbose_name='Vai trò')),
                ('event_type', models.CharField(choices=[('reconnecting', 'Đang kết nối lại'), ('reconnected', 'Kết nối lại thành công'), ('disconnected', 'Mất kết nối'), ('connection_dropped', 'Rớt kết nối đột ngột'), ('failed', 'Kết nối thất bại')], max_length=50, verbose_name='Loại sự kiện kết nối')),
                ('downtime_seconds', models.FloatField(default=0.0, verbose_name='Thời gian gián đoạn tính bằng giây')),
                ('reconnect_attempt', models.PositiveIntegerField(default=1, verbose_name='Lần thử kết nối lại')),
                ('network_quality', models.CharField(blank=True, default='', max_length=30, verbose_name='Chất lượng mạng (poor/good/excellent)')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='Thông tin kỹ thuật chi tiết (RTT, packet loss, jitter)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời điểm ghi nhận')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_logs', to='interview.interviewsession', verbose_name='Buổi phỏng vấn')),
            ],
            options={
                'verbose_name': 'Interview Connection Log',
                'verbose_name_plural': 'Interview Connection Logs',
                'db_table': 'project_interview_connection_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
