# Generated by Django 4.2.30 on 2026-09-17 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0002_alter_file_file_type'),
        ('info', '0013_company_evaluation_weights'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('mode', models.CharField(choices=[('create', 'Create Only'), ('update', 'Update Only'), ('upsert', 'Upsert')], default='create', max_length=20)),
                ('match_by', models.CharField(default='default', max_length=64)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('validating', 'Validating'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('committing', 'Committing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='uploaded', max_length=30)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('warning_rows', models.PositiveIntegerField(default=0)),
                ('created_rows', models.PositiveIntegerField(default=0)),
                ('updated_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('current_step', models.CharField(blank=True, default='', max_length=150)),
                ('error_summary', models.JSONField(blank=True, default=list)),
                ('error_report_url', models.URLField(blank=True, max_length=500, null=True)),
                ('payload_cache_key', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_import_jobs', to='info.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_import_jobs', to=settings.AUTH_USER_MODEL)),
                ('error_report_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_import_error_reports', to='files.file')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_import_jobs', to='files.file')),
            ],
            options={
                'db_table': 'project_exchange_import_job',
                'ordering': ['-create_at'],
                'indexes': [models.Index(fields=['company', '-create_at'], name='idx_ex_imp_comp_created'), models.Index(fields=['public_id'], name='idx_ex_imp_public_id')],
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('format', models.CharField(default='xlsx', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=30)),
                ('selected_fields', models.JSONField(blank=True, default=list)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('current_step', models.CharField(blank=True, default='', max_length=150)),
                ('file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_export_jobs', to='info.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_export_jobs', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_export_jobs', to='files.file')),
            ],
            options={
                'db_table': 'project_exchange_export_job',
                'ordering': ['-create_at'],
                'indexes': [models.Index(fields=['company', '-create_at'], name='idx_ex_exp_comp_created'), models.Index(fields=['public_id'], name='idx_ex_exp_public_id')],
            },
        ),
    ]
