# Generated by Django 4.2 on 2026-08-29
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecv',
            name='ai_score',
            field=models.PositiveIntegerField(blank=True, help_text='Điểm đánh giá ATS từ 0-100', null=True),
        ),
        migrations.AddField(
            model_name='candidatecv',
            name='ai_review_data',
            field=models.JSONField(blank=True, default=dict, help_text='Chi tiết phân tích & gợi ý cải thiện từ AI'),
        ),
    ]
