# Generated by Django 4.2.30 on 2026-08-31 10:13

import autoslug.fields
from django.db import migrations
import django.utils.text


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0002_candidatecv_ai_score_and_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatecv',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='title', slugify=django.utils.text.slugify, unique_with=['id']),
        ),
    ]
