# Generated by Django 4.2.29 on 2026-03-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('format', models.CharField(max_length=50)),
                ('resource_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('raw', 'Raw File')], max_length=50)),
                ('file_type', models.CharField(choices=[('AVATAR', 'Avatar'), ('CV', 'CV'), ('LOGO', 'Logo'), ('COVER_IMAGE', 'Cover Image'), ('COMPANY_IMAGE', 'Company Image'), ('CAREER_IMAGE', 'Career Image'), ('WEB_BANNER', 'Web Banner'), ('MOBILE_BANNER', 'Mobile Banner'), ('SYSTEM', 'System'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('uploaded_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_files',
                'ordering': ['-create_at'],
            },
        ),
    ]
