# Generated by Django 4.2.30 on 2026-08-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('AVATAR', 'Avatar'), ('CV', 'CV'), ('LOGO', 'Logo'), ('COVER_IMAGE', 'Cover Image'), ('COMPANY_IMAGE', 'Company Image'), ('CAREER_IMAGE', 'Career Image'), ('WEB_BANNER', 'Web Banner'), ('MOBILE_BANNER', 'Mobile Banner'), ('SYSTEM', 'System'), ('BUSINESS_LICENSE', 'Business License'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
