import AccessTimeSharpIcon from '@mui/icons-material/AccessTimeSharp';
import ArrowForwardSharpIcon from '@mui/icons-material/ArrowForwardSharp';
import AttachMoneySharpIcon from '@mui/icons-material/AttachMoneySharp';
import AutoAwesomeSharpIcon from '@mui/icons-material/AutoAwesomeSharp';
import AutoFixHighSharpIcon from '@mui/icons-material/AutoFixHighSharp';
import BoltSharpIcon from '@mui/icons-material/BoltSharp';
import BusinessSharpIcon from '@mui/icons-material/BusinessSharp';
import CalendarMonthSharpIcon from '@mui/icons-material/CalendarMonthSharp';
import CheckCircleSharpIcon from '@mui/icons-material/CheckCircleSharp';
import ChevronRightSharpIcon from '@mui/icons-material/ChevronRightSharp';
import ConstructionSharpIcon from '@mui/icons-material/ConstructionSharp';
import DescriptionSharpIcon from '@mui/icons-material/DescriptionSharp';
import EmailSharpIcon from '@mui/icons-material/EmailSharp';
import ErrorSharpIcon from '@mui/icons-material/ErrorSharp';
import EventSharpIcon from '@mui/icons-material/EventSharp';
import FormatListBulletedSharpIcon from '@mui/icons-material/FormatListBulletedSharp';
import FormatQuoteSharpIcon from '@mui/icons-material/FormatQuoteSharp';
import GroupsSharpIcon from '@mui/icons-material/GroupsSharp';
import HomeWorkSharpIcon from '@mui/icons-material/HomeWorkSharp';
import LocalOfferSharpIcon from '@mui/icons-material/LocalOfferSharp';
import LocalPhoneSharpIcon from '@mui/icons-material/LocalPhoneSharp';
import LocationOnSharpIcon from '@mui/icons-material/LocationOnSharp';
import MapSharpIcon from '@mui/icons-material/MapSharp';
import PaidSharpIcon from '@mui/icons-material/PaidSharp';
import PictureAsPdfSharpIcon from '@mui/icons-material/PictureAsPdfSharp';
import PersonSharpIcon from '@mui/icons-material/PersonSharp';
import PublicSharpIcon from '@mui/icons-material/PublicSharp';
import SchoolSharpIcon from '@mui/icons-material/SchoolSharp';
import VisibilitySharpIcon from '@mui/icons-material/VisibilitySharp';
import WarningAmberSharpIcon from '@mui/icons-material/WarningAmberSharp';
import WhatshotSharpIcon from '@mui/icons-material/WhatshotSharp';
import WcSharpIcon from '@mui/icons-material/WcSharp';
import WorkSharpIcon from '@mui/icons-material/WorkSharp';

export const faArrowRight = ArrowForwardSharpIcon;
export const faBriefcase = WorkSharpIcon;
export const faBuilding = BusinessSharpIcon; // Fixed typo
export const faCalendarAlt = CalendarMonthSharpIcon;
export const faCalendarDay = EventSharpIcon;
export const faCalendarDays = CalendarMonthSharpIcon;
export const faCheckCircle = CheckCircleSharpIcon;
export const faChevronRight = ChevronRightSharpIcon;
export const faCircleDollarToSlot = PaidSharpIcon;
export const faCircleExclamation = ErrorSharpIcon;
export const faClock = AccessTimeSharpIcon;
export const faClockFour = AccessTimeSharpIcon;
export const faDollarSign = AttachMoneySharpIcon;
export const faEnvelope = EmailSharpIcon;
export const faFire = WhatshotSharpIcon;
export const faFontAwesome = AutoAwesomeSharpIcon;
export const faGlobe = PublicSharpIcon;
export const faGraduationCap = SchoolSharpIcon;
export const faHashtag = LocalOfferSharpIcon;
export const faListUl = FormatListBulletedSharpIcon;
export const faLocationDot = LocationOnSharpIcon;
export const faMagicWandSparkles = AutoFixHighSharpIcon;
export const faMapLocation = MapSharpIcon;
export const faPersonDigging = ConstructionSharpIcon;
export const faPhoneVolume = LocalPhoneSharpIcon;
export const faUsers = GroupsSharpIcon;
export const faUser = PersonSharpIcon;
export const faVenusMars = WcSharpIcon;
export const faPeopleRoof = HomeWorkSharpIcon;
export const faQuoteLeft = FormatQuoteSharpIcon;
export const faWarning = WarningAmberSharpIcon;
export const faEye = VisibilitySharpIcon;
export const faBolt = BoltSharpIcon;
export const faFile = DescriptionSharpIcon;
export const faFilePdf = PictureAsPdfSharpIcon;
export const faLocation = LocationOnSharpIcon;
export const faCalendar = CalendarMonthSharpIcon;
export const faUserGroup = GroupsSharpIcon;
export const faCheck = CheckCircleSharpIcon;
