import FileCopySharpIcon from '@mui/icons-material/FileCopySharp';
import DeleteSharpIcon from '@mui/icons-material/DeleteSharp';
import EditSharpIcon from '@mui/icons-material/EditSharp';
import VisibilitySharpIcon from '@mui/icons-material/VisibilitySharp';
import BlockSharpIcon from '@mui/icons-material/BlockSharp';
import CheckCircleSharpIcon from '@mui/icons-material/CheckCircleSharp';
import CloseSharpIcon from '@mui/icons-material/CloseSharp';
import ExitToAppSharpIcon from '@mui/icons-material/ExitToAppSharp';
import MarkEmailReadSharpIcon from '@mui/icons-material/MarkEmailReadSharp';
import DeleteOutlineSharpIcon from '@mui/icons-material/DeleteOutlineSharp';
import CheckSharpIcon from '@mui/icons-material/CheckSharp';
import ClearSharpIcon from '@mui/icons-material/ClearSharp';
import ArrowRightAltSharpIcon from '@mui/icons-material/ArrowRightAltSharp';
import BoltSharpIcon from '@mui/icons-material/BoltSharp';
import WorkSharpIcon from '@mui/icons-material/WorkSharp';
import ApartmentSharpIcon from '@mui/icons-material/ApartmentSharp';
import CalendarMonthSharpIcon from '@mui/icons-material/CalendarMonthSharp';
import ChevronRightSharpIcon from '@mui/icons-material/ChevronRightSharp';
import PaidSharpIcon from '@mui/icons-material/PaidSharp';
import AccessTimeSharpIcon from '@mui/icons-material/AccessTimeSharp';
import AttachMoneySharpIcon from '@mui/icons-material/AttachMoneySharp';
import InsertDriveFileSharpIcon from '@mui/icons-material/InsertDriveFileSharp';
import PictureAsPdfSharpIcon from '@mui/icons-material/PictureAsPdfSharp';
import LocalFireDepartmentSharpIcon from '@mui/icons-material/LocalFireDepartmentSharp';
import AutoAwesomeSharpIcon from '@mui/icons-material/AutoAwesomeSharp';
import PublicSharpIcon from '@mui/icons-material/PublicSharp';
import SchoolSharpIcon from '@mui/icons-material/SchoolSharp';
import TagSharpIcon from '@mui/icons-material/TagSharp';
import FormatListBulletedSharpIcon from '@mui/icons-material/FormatListBulletedSharp';
import PlaceSharpIcon from '@mui/icons-material/PlaceSharp';
import AutoFixHighSharpIcon from '@mui/icons-material/AutoFixHighSharp';
import MapSharpIcon from '@mui/icons-material/MapSharp';
import PeopleSharpIcon from '@mui/icons-material/PeopleSharp';
import EngineeringSharpIcon from '@mui/icons-material/EngineeringSharp';
import PhoneSharpIcon from '@mui/icons-material/PhoneSharp';
import FormatQuoteSharpIcon from '@mui/icons-material/FormatQuoteSharp';
import PersonSharpIcon from '@mui/icons-material/PersonSharp';
import WcSharpIcon from '@mui/icons-material/WcSharp';
import WarningAmberSharpIcon from '@mui/icons-material/WarningAmberSharp';

export const faClone = FileCopySharpIcon;
export const faTrashAlt = DeleteSharpIcon;
export const faEdit = EditSharpIcon;
export const faEye = VisibilitySharpIcon;
export const faBan = BlockSharpIcon;
export const faCheckCircle = CheckCircleSharpIcon;
export const faTimes = CloseSharpIcon;
export const faSignOutAlt = ExitToAppSharpIcon;
export const faEnvelope = MarkEmailReadSharpIcon;
export const faTimesCircle = DeleteOutlineSharpIcon;
export const faCheck = CheckSharpIcon;
export const faTimesCircleRegular = ClearSharpIcon;
export const faArrowRight = ArrowRightAltSharpIcon;
export const faBolt = BoltSharpIcon;
export const faBriefcase = WorkSharpIcon;
export const faBuilding = ApartmentSharpIcon;
export const faCalendar = CalendarMonthSharpIcon;
export const faCalendarAlt = CalendarMonthSharpIcon;
export const faCalendarDay = CalendarMonthSharpIcon;
export const faCalendarDays = CalendarMonthSharpIcon;
export const faChevronRight = ChevronRightSharpIcon;
export const faCircleDollarToSlot = PaidSharpIcon;
export const faClock = AccessTimeSharpIcon;
export const faClockFour = AccessTimeSharpIcon;
export const faDollarSign = AttachMoneySharpIcon;
export const faFile = InsertDriveFileSharpIcon;
export const faFilePdf = PictureAsPdfSharpIcon;
export const faFire = LocalFireDepartmentSharpIcon;
export const faFontAwesome = AutoAwesomeSharpIcon;
export const faGlobe = PublicSharpIcon;
export const faGraduationCap = SchoolSharpIcon;
export const faHashtag = TagSharpIcon;
export const faListUl = FormatListBulletedSharpIcon;
export const faLocationDot = PlaceSharpIcon;
export const faMagicWandSparkles = AutoFixHighSharpIcon;
export const faMapLocation = MapSharpIcon;
export const faPeopleRoof = PeopleSharpIcon;
export const faPersonDigging = EngineeringSharpIcon;
export const faPhoneVolume = PhoneSharpIcon;
export const faQuoteLeft = FormatQuoteSharpIcon;
export const faUser = PersonSharpIcon;
export const faUsers = PeopleSharpIcon;
export const faVenusMars = WcSharpIcon;
export const faWarning = WarningAmberSharpIcon;
