# Generated by Django 4.2.29 on 2026-03-19 03:23

import autoslug.fields
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=300, populate_from='company_name', slugify=django.utils.text.slugify, unique_with=['id'])),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('company_email', models.EmailField(max_length=100, unique=True)),
                ('company_phone', models.CharField(max_length=15, unique=True)),
                ('website_url', models.URLField(blank=True, max_length=300, null=True)),
                ('tax_code', models.CharField(max_length=30, unique=True)),
                ('since', models.DateField(null=True)),
                ('field_operation', models.CharField(blank=True, max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('employee_size', models.SmallIntegerField(choices=[(1, 'Under 10 employees'), (2, '10 - 150 employees'), (3, '150 - 300 employees'), (4, 'Over 300 employees')], null=True)),
                ('cover_image', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_cover_image', to='files.file')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'project_info_company',
            },
        ),
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('birthday', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married')], default='S', max_length=1, null=True)),
                ('id_card_number', models.CharField(blank=True, max_length=30, null=True)),
                ('id_card_issue_date', models.DateField(blank=True, null=True)),
                ('id_card_issue_place', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_code', models.CharField(blank=True, max_length=30, null=True)),
                ('social_insurance_no', models.CharField(blank=True, max_length=30, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_address', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_seeker_profiles', to='locations.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_info_job_seeker_profile',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=django.utils.text.slugify, unique_with=['id'])),
                ('description', models.TextField(null=True)),
                ('salary_min', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('salary_max', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('skills_summary', models.TextField(blank=True, null=True)),
                ('position', models.SmallIntegerField(choices=[(1, 'Senior Management'), (2, 'Middle Management'), (3, 'Team Leader - Supervisor'), (4, 'Specialist'), (5, 'Staff / Employee'), (6, 'Collaborator')], null=True)),
                ('experience', models.SmallIntegerField(choices=[(1, 'No experience'), (2, 'Under 1 year'), (3, '1 year'), (4, '2 years'), (5, '3 years'), (6, '4 years'), (7, '5 years'), (8, 'Over 5 years')], null=True)),
                ('academic_level', models.SmallIntegerField(choices=[(1, 'Postgraduate'), (2, 'University'), (3, 'College'), (4, 'Vocational / Intermediate'), (5, 'High School'), (6, 'Certificate')], null=True)),
                ('type_of_workplace', models.SmallIntegerField(choices=[(1, 'Office-based'), (2, 'Hybrid'), (3, 'Remote / Work from home')], null=True)),
                ('job_type', models.SmallIntegerField(choices=[(1, 'Full-time Permanent'), (2, 'Full-time Temporary'), (3, 'Part-time Permanent'), (4, 'Part-time Temporary'), (5, 'Consultancy Contract'), (6, 'Internship'), (7, 'Other')], null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('type', models.CharField(default='UPLOAD', max_length=10)),
                ('career', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='common.career')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='locations.city')),
            ],
            options={
                'db_table': 'project_info_resume',
            },
        ),
        migrations.CreateModel(
            name='ResumeViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('views', models.BigIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.company')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.resume')),
            ],
            options={
                'verbose_name_plural': 'Resumes viewed',
                'db_table': 'project_info_resume_viewed',
            },
        ),
        migrations.CreateModel(
            name='ResumeSaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.company')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.resume')),
            ],
            options={
                'verbose_name_plural': 'Resumes saved',
                'db_table': 'project_info_resume_saved',
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='company_savers',
            field=models.ManyToManyField(related_name='resumes_saved', through='info.ResumeSaved', to='info.company'),
        ),
        migrations.AddField(
            model_name='resume',
            name='company_viewers',
            field=models.ManyToManyField(related_name='resumes_viewed', through='info.ResumeViewed', to='info.company'),
        ),
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_file', to='files.file'),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_seeker_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='info.jobseekerprofile'),
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LanguageSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('language', models.SmallIntegerField(choices=[(1, 'Vietnamese'), (2, 'English'), (3, 'Japanese'), (4, 'French'), (5, 'Chinese'), (6, 'Russian'), (7, 'Korean'), (8, 'German'), (9, 'Italian'), (10, 'Arabic'), (11, 'Other')])),
                ('level', models.SmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')])),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_skills', to='info.resume')),
            ],
            options={
                'db_table': 'project_info_language_skill',
            },
        ),
        migrations.CreateModel(
            name='ExperienceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('job_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('last_salary', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('leave_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_details', to='info.resume')),
            ],
            options={
                'db_table': 'project_info_experience_detail',
            },
        ),
        migrations.CreateModel(
            name='EducationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('degree_name', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=255)),
                ('training_place_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('completed_date', models.DateField(null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('grade_or_rank', models.CharField(blank=True, max_length=100, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_details', to='info.resume')),
            ],
            options={
                'db_table': 'project_info_education_detail',
            },
        ),
        migrations.CreateModel(
            name='ContactProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.company')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.resume')),
            ],
            options={
                'verbose_name_plural': 'Contact profiles',
                'db_table': 'project_info_contact_profile',
            },
        ),
        migrations.CreateModel(
            name='CompanyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='info.company')),
            ],
            options={
                'db_table': 'project_info_company_role',
            },
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=10)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('invited_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='info.company')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='info.companyrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_info_company_member',
            },
        ),
        migrations.CreateModel(
            name='CompanyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_images', to='info.company')),
                ('image', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_image', to='files.file')),
            ],
            options={
                'db_table': 'project_info_company_image',
            },
        ),
        migrations.CreateModel(
            name='CompanyFollowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies followed',
                'db_table': 'project_info_company_followed',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='followers',
            field=models.ManyToManyField(related_name='companies_followed', through='info.CompanyFollowed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='locations.location'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_logo', to='files.file'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('training_place', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='info.resume')),
            ],
            options={
                'db_table': 'project_info_certificate',
            },
        ),
        migrations.CreateModel(
            name='AdvancedSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('level', models.SmallIntegerField(default=3)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_skills', to='info.resume')),
            ],
            options={
                'db_table': 'project_info_advanced_skill',
            },
        ),
        migrations.AddConstraint(
            model_name='companyrole',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_company_role_code'),
        ),
        migrations.AddConstraint(
            model_name='companyrole',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uq_company_role_name'),
        ),
        migrations.AddConstraint(
            model_name='companymember',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='uq_company_member_company_user'),
        ),
    ]
