# Generated by Django 4.2.29 on 2026-03-21 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterUniqueTogether(
            name='companyfollowed',
            unique_together={('user', 'company')},
        ),
        migrations.AddIndex(
            model_name='companyfollowed',
            index=models.Index(fields=['user', 'company'], name='idx_followed_user_company'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['is_active', '-update_at'], name='idx_resume_active_updated'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', 'is_active'], name='idx_resume_user_active'),
        ),
    ]
