# Generated by Django 4.2.30 on 2026-07-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_company_hr_manage_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_imported',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='source_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='source_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='source_platform',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='source_ref',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
