# Generated by Django 4.2.30 on 2026-07-09 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
        ('info', '0009_resume_source_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('source_url', models.URLField()),
                ('source_account', models.CharField(max_length=255)),
                ('occupation_ids', models.JSONField(blank=True, default=list)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('source_payload', models.JSONField(blank=True, null=True)),
                ('result_payload', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vieclam24h_import_jobs', to=settings.AUTH_USER_MODEL)),
                ('target_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vieclam24h_import_jobs', to='locations.city')),
                ('target_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vieclam24h_import_jobs', to='locations.district')),
            ],
            options={
                'db_table': 'project_info_resume_import_job',
                'indexes': [models.Index(fields=['status', '-create_at'], name='idx_resimp_status_ctd')],
            },
        ),
    ]
