# Generated by Django 4.2.30 on 2026-08-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_resumeimportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='is_seeking_job',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
