# Generated by Django 4.2.30 on 2026-08-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_jobseekerprofile_is_seeking_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='type',
            field=models.CharField(db_index=True, default='UPLOAD', max_length=10),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['is_active', 'type'], name='idx_resume_active_type'),
        ),
    ]
