# Generated by Django 4.2.29 on 2026-03-18 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('locations', '0001_initial'),
        ('info', '0011_company_role_company_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cover_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_cover_image', to='files.file'),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_logo', to='files.file'),
        ),
        migrations.AlterField(
            model_name='companyimage',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_image', to='files.file'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_seeker_profiles', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='locations.city'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_file', to='files.file'),
        ),
    ]
