# Generated by Django 4.2.30 on 2026-09-17 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_file_type'),
        ('info', '0013_company_evaluation_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_seeker_cover_image', to='files.file'),
        ),
    ]
