# Generated by Django 4.2.30 on 2026-09-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_jobseekerprofile_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ai_settings',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Cấu hình Trợ lý AI phỏng vấn của doanh nghiệp'),
        ),
    ]
