# Generated by Django 6.0.3 on 2026-03-08 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0009_alter_jobpost_academic_level_alter_jobpost_job_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('room_name', models.CharField(max_length=255, unique=True, verbose_name='Tên phòng (LiveKit Room)')),
                ('invite_token', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Token mời phỏng vấn')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('scheduled', 'Đã lên lịch'), ('calibration', 'Kiểm tra thiết bị'), ('in_progress', 'Đang phỏng vấn'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy'), ('interrupted', 'Bị gián đoạn'), ('processing', 'Đang xử lý')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('type', models.CharField(choices=[('technical', 'Kỹ thuật'), ('behavioral', 'Hành vi'), ('mixed', 'Tổng hợp')], default='mixed', max_length=20, verbose_name='Loại phỏng vấn')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian dự kiến')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Bắt đầu lúc')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Kết thúc lúc')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Thời lượng (giây)')),
                ('recording_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link video ghi hình')),
                ('transcript_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link transcript')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('ai_overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Điểm tổng AI')),
                ('ai_technical_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Điểm kỹ thuật AI')),
                ('ai_communication_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Điểm giao tiếp AI')),
                ('ai_summary', models.TextField(blank=True, null=True, verbose_name='Nhận xét AI')),
                ('ai_strengths', models.JSONField(blank=True, null=True, verbose_name='Điểm mạnh (AI)')),
                ('ai_weaknesses', models.JSONField(blank=True, null=True, verbose_name='Điểm yếu (AI)')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Ứng viên')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interviews', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo (HR)')),
                ('job_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to='job.jobpost', verbose_name='Tin tuyển dụng')),
            ],
            options={
                'verbose_name': 'Interview Session',
                'verbose_name_plural': 'Interview Sessions',
                'db_table': 'myjob_interview_session',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('attitude_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Điểm thái độ')),
                ('professional_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Điểm chuyên môn')),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Điểm tổng')),
                ('result', models.CharField(choices=[('passed', 'Đạt'), ('failed', 'Không đạt'), ('pending', 'Chờ đánh giá')], default='pending', max_length=20, verbose_name='Kết quả')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Nhận xét')),
                ('proposed_salary', models.IntegerField(blank=True, null=True, verbose_name='Mức lương đề xuất')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='interview.interviewsession', verbose_name='Buổi phỏng vấn')),
            ],
            options={
                'verbose_name': 'Interview Evaluation',
                'verbose_name_plural': 'Interview Evaluations',
                'db_table': 'myjob_interview_evaluation',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_role', models.CharField(choices=[('ai_agent', 'AI Agent'), ('candidate', 'Ứng viên')], max_length=20, verbose_name='Vai trò người nói')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('speech_duration_ms', models.IntegerField(blank=True, null=True, verbose_name='Thời lượng nói (ms)')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='interview.interviewsession', verbose_name='Buổi phỏng vấn')),
            ],
            options={
                'verbose_name': 'Interview Transcript',
                'verbose_name_plural': 'Interview Transcripts',
                'db_table': 'myjob_interview_transcript',
                'ordering': ['create_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='Nội dung câu hỏi')),
                ('category', models.CharField(choices=[('soft_skills', 'Kỹ năng mềm'), ('technical', 'Kỹ thuật'), ('behavioral', 'Hành vi'), ('situational', 'Tình huống'), ('general', 'Chung')], default='general', max_length=20, verbose_name='Danh mục')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'myjob_interview_question',
                'ordering': ['sort_order', '-create_at'],
            },
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='interview_sessions', to='interview.question', verbose_name='Câu hỏi'),
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Tên nhóm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_question_groups', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('questions', models.ManyToManyField(blank=True, related_name='groups', to='interview.question', verbose_name='Câu hỏi')),
            ],
            options={
                'verbose_name': 'Question Group',
                'verbose_name_plural': 'Question Groups',
                'db_table': 'myjob_interview_question_group',
                'ordering': ['-create_at'],
            },
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='question_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to='interview.questiongroup', verbose_name='Nhóm câu hỏi'),
        ),
    ]
