# Generated by Django 6.0.3 on 2026-03-09 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_file_file_type'),
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='common.career', verbose_name='Lĩnh vực'),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Dễ'), (2, 'Trung bình'), (3, 'Khó')], default=1, verbose_name='Mức độ'),
        ),
    ]
