# Generated by Django 4.2.29 on 2026-03-09 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_alter_company_employee_size_and_more'),
        ('interview', '0002_question_career_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='info.company', verbose_name='Thuộc công ty'),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='info.company', verbose_name='Thuộc công ty'),
        ),
    ]
