# Generated by Django 4.2.29 on 2026-03-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_interviewsession_question_cursor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='question_cursor',
            field=models.IntegerField(default=0, verbose_name='Ch??? s??? c??u h???i hi???n t???i'),
        ),
    ]
