# Generated by Django 4.2.29 on 2026-03-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('button_text', models.TextField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('is_show_button', models.BooleanField(default=False)),
                ('description_location', models.IntegerField(choices=[(1, 'TOP_LEFT'), (2, 'TOP_RIGHT'), (3, 'BOTTOM_LEFT'), (4, 'BOTTOM_RIGHT')], default=3)),
                ('platform', models.CharField(choices=[('WEB', 'Website'), ('APP', 'Application')], default=1, max_length=3)),
                ('type', models.IntegerField(choices=[(1, 'HOME'), (2, 'MAIN_JOB_RIGHT')], default=1)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'project_project_banner',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=500)),
                ('rating', models.SmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'project_project_feedback',
            },
        ),
    ]
