# Generated by Django 4.2.29 on 2026-03-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField(default='')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'System settings',
                'db_table': 'project_project_system_setting',
            },
        ),
    ]
