# Generated by Django 4.2.29 on 2026-03-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_remove_banner_image_mobile_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='platform',
            field=models.CharField(choices=[('WEB', 'Website'), ('APP', 'Application')], default=1, max_length=3),
        ),
    ]

