# Generated by Django 4.2.29 on 2026-03-18 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('Project', '0004_alter_banner_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_image', to='files.file'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_mobile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_image_mobile', to='files.file'),
        ),
    ]
