# Generated by Django 4.2.30 on 2026-06-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_feedback_evidence_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='platform',
            field=models.CharField(choices=[('WEB', 'Website'), ('APP', 'Application')], default='WEB', max_length=3),
        ),
    ]
