# Generated by Django 4.2.30 on 2026-06-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_alter_feedback_user_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='category',
            field=models.CharField(choices=[('bug_report', 'Báo lỗi'), ('feedback', 'Góp ý'), ('support', 'Liên hệ hỗ trợ')], db_index=True, default='bug_report', max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='page_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
