# Generated by Django 4.2.30 on 2026-08-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0009_contactmessage_category_contactmessage_page_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('news', 'Tin tức'), ('blog', 'Blog tuyển dụng'), ('cam-nang', 'Cẩm nang nghề nghiệp'), ('thu-tuc-lao-dong', 'Thủ tục & Quyền lợi lao động'), ('thue-tncn', 'Thuế & Quyết toán TNCN'), ('bi-quyet-cv', 'Bí quyết viết CV & Phỏng vấn'), ('xu-huong', 'Báo cáo & Xu hướng tuyển dụng')], db_index=True, default='news', max_length=50),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
