# Generated by Django 4.2.29 on 2026-03-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_alter_jobpost_academic_level_alter_jobpost_job_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostactivity',
            name='ai_analysis_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpostactivity',
            name='ai_analysis_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpostactivity',
            name='ai_analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='jobpostactivity',
            name='ai_analysis_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
