# Generated by Django 4.2.29 on 2026-03-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_jobpostactivity_ai_analysis_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='academic_level',
            field=models.SmallIntegerField(choices=[(1, 'Postgraduate'), (2, 'University'), (3, 'College'), (4, 'Vocational / Intermediate'), (5, 'High School'), (6, 'Certificate')]),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='experience',
            field=models.SmallIntegerField(choices=[(1, 'No experience'), (2, 'Under 1 year'), (3, '1 year'), (4, '2 years'), (5, '3 years'), (6, '4 years'), (7, '5 years'), (8, 'Over 5 years')]),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='gender_required',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.SmallIntegerField(choices=[(1, 'Full-time Permanent'), (2, 'Full-time Temporary'), (3, 'Part-time Permanent'), (4, 'Part-time Temporary'), (5, 'Consultancy Contract'), (6, 'Internship'), (7, 'Other')]),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='position',
            field=models.SmallIntegerField(choices=[(1, 'Senior Management'), (2, 'Middle Management'), (3, 'Team Leader - Supervisor'), (4, 'Specialist'), (5, 'Staff / Employee'), (6, 'Collaborator')]),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Rejected'), (3, 'Approved')], default=1),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='type_of_workplace',
            field=models.SmallIntegerField(choices=[(1, 'Office-based'), (2, 'Hybrid'), (3, 'Remote / Work from home')]),
        ),
        migrations.AlterField(
            model_name='jobpostactivity',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending Confirmation'), (2, 'Contacted'), (3, 'Tested'), (4, 'Interviewed'), (5, 'Hired'), (6, 'Not Selected')], default=1),
        ),
        migrations.AlterField(
            model_name='jobpostnotification',
            name='experience',
            field=models.SmallIntegerField(choices=[(1, 'No experience'), (2, 'Under 1 year'), (3, '1 year'), (4, '2 years'), (5, '3 years'), (6, '4 years'), (7, '5 years'), (8, 'Over 5 years')], null=True),
        ),
        migrations.AlterField(
            model_name='jobpostnotification',
            name='frequency',
            field=models.IntegerField(choices=[(1, 'Daily'), (2, 'Every 3 Days'), (3, 'Weekly')]),
        ),
        migrations.AlterField(
            model_name='jobpostnotification',
            name='position',
            field=models.SmallIntegerField(choices=[(1, 'Senior Management'), (2, 'Middle Management'), (3, 'Team Leader - Supervisor'), (4, 'Specialist'), (5, 'Staff / Employee'), (6, 'Collaborator')], null=True),
        ),
    ]
