# Generated by Django 4.2.29 on 2026-03-19 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('app_icon_name', models.CharField(max_length=50, null=True)),
                ('is_hot', models.BooleanField(default=False)),
                ('icon', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.file')),
            ],
            options={
                'db_table': 'project_common_career',
            },
        ),
    ]
