# Generated by Django on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verify_phone',
            field=models.BooleanField(default=False),
        ),
    ]
