# Generated by Django 4.2.30 on 2026-08-24 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_alter_resume_type_resume_idx_resume_active_type'),
        ('hrm', '0002_employee_onboarded_from_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField(verbose_name='Tháng')),
                ('year', models.PositiveIntegerField(verbose_name='Năm')),
                ('gross_salary', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Lương Gross')),
                ('allowance', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Phụ cấp')),
                ('bonus', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Thưởng')),
                ('working_days_actual', models.PositiveSmallIntegerField(default=22, verbose_name='Ngày công thực tế')),
                ('standard_working_days', models.PositiveSmallIntegerField(default=22, verbose_name='Ngày công chuẩn')),
                ('unpaid_leave_days', models.PositiveSmallIntegerField(default=0, verbose_name='Ngày nghỉ không lương')),
                ('total_income', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng thu nhập')),
                ('bhxh_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='BHXH (8%)')),
                ('bhyt_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='BHYT (1.5%)')),
                ('bhtn_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='BHTN (1%)')),
                ('total_insurance', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng bảo hiểm')),
                ('taxable_income', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Thu nhập tính thuế')),
                ('personal_income_tax', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Thuế TNCN')),
                ('net_salary', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Lương thực nhận (Net)')),
                ('status', models.CharField(choices=[('DRAFT', 'Bản nháp'), ('APPROVED', 'Đã phê duyệt'), ('PAID', 'Đã chi trả')], db_index=True, default='DRAFT', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ngày thanh toán')),
                ('note', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='info.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='hrm.employee')),
            ],
            options={
                'ordering': ['-year', '-month', 'employee'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
