# Generated by Django on 2026-08-30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_monthlypayrollrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayrollrecord',
            name='dependents_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Số người phụ thuộc'),
        ),
        migrations.AddField(
            model_name='monthlypayrollrecord',
            name='employer_bhxh',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='BHXH NSDLĐ (17.5%)'),
        ),
        migrations.AddField(
            model_name='monthlypayrollrecord',
            name='employer_bhyt',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='BHYT NSDLĐ (3%)'),
        ),
        migrations.AddField(
            model_name='monthlypayrollrecord',
            name='employer_bhtn',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='BHTN NSDLĐ (1%)'),
        ),
        migrations.AddField(
            model_name='monthlypayrollrecord',
            name='employer_union_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Kinh phí Công đoàn (2%)'),
        ),
        migrations.AddField(
            model_name='monthlypayrollrecord',
            name='total_employer_insurance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng BH NSDLĐ'),
        ),
        migrations.AddField(
            model_name='monthlypayrollrecord',
            name='total_company_expense',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng chi phí Doanh nghiệp'),
        ),
        migrations.AlterField(
            model_name='monthlypayrollrecord',
            name='total_insurance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng BH NLĐ'),
        ),
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('year', models.PositiveIntegerField(verbose_name='Năm')),
                ('allocated_days', models.DecimalField(decimal_places=1, default=12.0, max_digits=5, verbose_name='Phép tiêu chuẩn')),
                ('seniority_bonus_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Phép thâm niên')),
                ('carried_over_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Phép tồn năm trước')),
                ('used_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Đã sử dụng')),
                ('pending_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Đang chờ duyệt')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hrm.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_balances', to='hrm.leavetype')),
            ],
            options={
                'ordering': ['-year', 'employee'],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
