# Generated by Django 4.2.30 on 2026-09-10 03:42

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_alter_resume_type_resume_idx_resume_active_type'),
        ('hrm', '0004_employeeleavebalance_and_payroll_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='adjustment_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='early_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='effective_work_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_manually_adjusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='late_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='scheduled_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='scheduled_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='status_code',
            field=models.CharField(blank=True, default='X', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, verbose_name='Mã ca')),
                ('name', models.CharField(max_length=100, verbose_name='Tên ca')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Nghỉ trưa từ')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Nghỉ trưa đến')),
                ('working_hours', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=4, verbose_name='Số giờ công')),
                ('work_factor', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3, verbose_name='Hệ số công')),
                ('is_overnight', models.BooleanField(default=False, verbose_name='Ca qua đêm')),
                ('grace_period_late_minutes', models.PositiveIntegerField(default=5, verbose_name='Dung sai đi muộn (phút)')),
                ('grace_period_early_minutes', models.PositiveIntegerField(default=5, verbose_name='Dung sai về sớm (phút)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_shifts', to='info.company')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='BiometricPunchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('biometric_id', models.CharField(max_length=50, verbose_name='Mã máy chấm công')),
                ('punch_time', models.DateTimeField(db_index=True, verbose_name='Thời gian quẹt')),
                ('device_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên máy chấm công')),
                ('device_ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP máy chấm công')),
                ('punch_type', models.CharField(choices=[('CHECK_IN', 'Vào'), ('CHECK_OUT', 'Ra'), ('AUTO', 'Tự động')], default='AUTO', max_length=20, verbose_name='Loại quẹt')),
                ('source', models.CharField(choices=[('ZKTECO', 'Máy ZKTeco'), ('EXCEL_IMPORT', 'Nhập file Excel'), ('WEB_APP', 'Web App'), ('MANUAL', 'Thủ công')], default='ZKTECO', max_length=20, verbose_name='Nguồn dữ liệu')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_logs', to='info.company')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punch_logs', to='hrm.employee')),
            ],
            options={
                'ordering': ['-punch_time'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('LEAVE', 'Đơn xin nghỉ'), ('REGULARISATION', 'Đề nghị cập nhật công'), ('BUSINESS_TRIP', 'Đề nghị công tác'), ('OVERTIME', 'Đơn làm thêm giờ'), ('LATE_EARLY', 'Đơn đi muộn về sớm')], db_index=True, max_length=30, verbose_name='Loại đơn')),
                ('start_date', models.DateField(verbose_name='Từ ngày')),
                ('end_date', models.DateField(verbose_name='Đến ngày')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Từ giờ')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Đến giờ')),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Số giờ')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Lý do')),
                ('status', models.CharField(choices=[('PENDING_STAGE_1', 'Chờ Quản lý duyệt'), ('APPROVED_STAGE_1', 'Quản lý đã duyệt - Chờ HR duyệt'), ('APPROVED', 'Đã phê duyệt'), ('REJECTED', 'Từ chối'), ('CANCELLED', 'Hủy đơn')], db_index=True, default='PENDING_STAGE_1', max_length=30, verbose_name='Trạng thái')),
                ('manager_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian quản lý duyệt')),
                ('hr_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian HR duyệt')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Lý do từ chối')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_requests', to='info.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_requests', to='hrm.employee')),
                ('hr_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests_stage2', to='hrm.employee', verbose_name='HR duyệt')),
                ('leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.leavetype', verbose_name='Loại phép')),
                ('manager_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests_stage1', to='hrm.employee', verbose_name='Quản lý duyệt')),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='hrm.workshift'),
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, verbose_name='Ngày làm việc')),
                ('is_off_day', models.BooleanField(default=False, verbose_name='Ngày nghỉ')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='info.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='hrm.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hrm.workshift')),
            ],
            options={
                'ordering': ['date', 'employee'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField(verbose_name='Tháng')),
                ('year', models.PositiveIntegerField(verbose_name='Năm')),
                ('standard_work_days', models.DecimalField(decimal_places=1, default=Decimal('22.0'), max_digits=4, verbose_name='Công chuẩn')),
                ('actual_work_days', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4, verbose_name='Công thực tế')),
                ('paid_leave_days', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4, verbose_name='Nghỉ phép hưởng lương')),
                ('unpaid_leave_days', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4, verbose_name='Nghỉ không lương')),
                ('overtime_hours_weekday', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='Giờ OT ngày thường')),
                ('overtime_hours_weekend', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='Giờ OT cuối tuần')),
                ('overtime_hours_holiday', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='Giờ OT lễ tết')),
                ('late_occurrences', models.PositiveSmallIntegerField(default=0, verbose_name='Số lần đi muộn')),
                ('early_occurrences', models.PositiveSmallIntegerField(default=0, verbose_name='Số lần về sớm')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Đã khóa')),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('pushed_to_payroll_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian chuyển tính lương')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_attendance_summaries', to='info.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_attendance_summaries', to='hrm.employee')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_summaries', to='hrm.employee')),
            ],
            options={
                'ordering': ['-year', '-month', 'employee'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
