# Generated by Django 4.2.30 on 2026-09-10 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_alter_resume_type_resume_idx_resume_active_type'),
        ('hrm', '0005_attendancerecord_adjustment_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricpunchlog',
            name='is_duplicate',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Cờ quẹt trùng lặp'),
        ),
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Tên trụ sở hoặc chi nhánh')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã chi nhánh')),
                ('location_type', models.CharField(choices=[('HEADQUARTERS', 'Trụ sở chính'), ('BRANCH', 'Chi nhánh'), ('FACTORY', 'Nhà xưởng / Nhà máy'), ('WAREHOUSE', 'Kho hàng'), ('RETAIL', 'Điểm bán lẻ / Showroom'), ('OTHER', 'Khác')], default='BRANCH', max_length=20, verbose_name='Phân loại địa điểm')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa chỉ')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tỉnh / Thành phố')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Vĩ độ')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Kinh độ')),
                ('radius_meters', models.PositiveIntegerField(default=200, verbose_name='Bán kính chấm công cho phép (mét)')),
                ('allowed_ip_ranges', models.TextField(blank=True, null=True, verbose_name='Dải IP mạng cho phép chấm công')),
                ('timezone', models.CharField(default='Asia/Ho_Chi_Minh', max_length=50, verbose_name='Múi giờ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_locations', to='info.company')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Tên máy chấm công')),
                ('device_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã thiết bị')),
                ('protocol', models.CharField(choices=[('ZKTECO_PULL', 'ZKTeco Kéo dữ liệu (TCP 4370)'), ('ZKTECO_PUSH', 'ZKTeco Đẩy tự động (ADMS / Cổng 4200)'), ('HIKVISION', 'Hikvision ISUP / ISAPI'), ('CAMERA_AI', 'Camera AI nhận diện khuôn mặt'), ('OTHER', 'Khác')], default='ZKTECO_PULL', max_length=30, verbose_name='Giao thức kết nối')),
                ('ip_or_domain', models.CharField(max_length=255, verbose_name='Địa chỉ IP hoặc tên miền')),
                ('device_port', models.PositiveIntegerField(default=4370, verbose_name='Cổng thiết bị phần cứng')),
                ('service_port', models.PositiveIntegerField(default=4200, verbose_name='Cổng dịch vụ máy chủ')),
                ('comm_key', models.CharField(blank=True, default='0', max_length=50, verbose_name='Mật mã kết nối (Comm Key)')),
                ('direction', models.CharField(choices=[('BOTH', 'Cả vào và ra'), ('IN', 'Chỉ quẹt vào'), ('OUT', 'Chỉ quẹt ra')], default='BOTH', max_length=10, verbose_name='Hướng quẹt')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Số sê-ri máy')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dòng máy / Hãng')),
                ('status', models.CharField(choices=[('ONLINE', 'Đang kết nối'), ('OFFLINE', 'Mất kết nối'), ('SYNCING', 'Đang đồng bộ'), ('ERROR', 'Lỗi kết nối')], default='OFFLINE', max_length=20, verbose_name='Trạng thái kết nối')),
                ('last_ping', models.DateTimeField(blank=True, null=True, verbose_name='Lần kiểm tra gần nhất')),
                ('last_sync_time', models.DateTimeField(blank=True, null=True, verbose_name='Lần đồng bộ gần nhất')),
                ('last_error_message', models.TextField(blank=True, null=True, verbose_name='Thông điệp lỗi gần nhất')),
                ('total_punches_synced', models.PositiveIntegerField(default=0, verbose_name='Tổng số lượt quẹt đã đồng bộ')),
                ('auto_sync_interval', models.PositiveIntegerField(default=15, verbose_name='Chu kỳ quét tự động (phút)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_devices', to='info.company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='hrm.worklocation', verbose_name='Trụ sở hoặc chi nhánh')),
            ],
            options={
                'ordering': ['location', 'name'],
                'unique_together': {('company', 'device_code')},
            },
        ),
        migrations.AddField(
            model_name='biometricpunchlog',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punch_logs', to='hrm.biometricdevice', verbose_name='Thiết bị chấm công'),
        ),
        migrations.AddField(
            model_name='biometricpunchlog',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punch_logs', to='hrm.worklocation', verbose_name='Trụ sở hoặc chi nhánh'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hrm.worklocation', verbose_name='Trụ sở hoặc chi nhánh'),
        ),
    ]
