# Generated by Django 4.2.30 on 2026-09-11 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_alter_resume_type_resume_idx_resume_active_type'),
        ('hrm', '0006_biometricpunchlog_is_duplicate_worklocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('IDENTITY_CARD', 'CCCD / Hộ chiếu'), ('LABOR_CONTRACT', 'Hợp đồng lao động bản scan'), ('DEGREE_CERTIFICATE', 'Bằng cấp / Chứng chỉ chuyên môn'), ('HEALTH_CERTIFICATE', 'Giấy khám sức khỏe định kỳ'), ('TAX_DOCUMENT', 'Mã số thuế / Giảm trừ gia cảnh'), ('DECISION', 'Quyết định bổ nhiệm / khen thưởng / kỷ luật'), ('OTHER', 'Tài liệu khác')], default='OTHER', max_length=30, verbose_name='Phân loại tài liệu')),
                ('name', models.CharField(max_length=255, verbose_name='Tên tài liệu')),
                ('file_url', models.URLField(max_length=500, verbose_name='Đường dẫn lưu trữ văn bản')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Ngày cấp')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn hiệu lực')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_documents', to='info.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hrm.employee')),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCareerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('effective_date', models.DateField(db_index=True, verbose_name='Ngày hiệu lực')),
                ('event_type', models.CharField(choices=[('ONBOARDING', 'Tiếp nhận / Tuyển dụng mới'), ('PROMOTION', 'Bổ nhiệm / Thăng chức'), ('TRANSFER', 'Điều chuyển phòng ban'), ('SALARY_ADJUSTMENT', 'Điều chỉnh lương'), ('ROLE_CHANGE', 'Thay đổi vị trí / Chức danh'), ('DEMOTION', 'Miễn nhiệm / Giáng chức'), ('RESIGNATION', 'Thôi việc / Nghỉ việc')], default='TRANSFER', max_length=30, verbose_name='Loại biến động')),
                ('old_salary', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Mức lương cũ')),
                ('new_salary', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Mức lương mới')),
                ('decision_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Số quyết định')),
                ('attachment', models.URLField(blank=True, max_length=500, null=True, verbose_name='Văn bản quyết định đính kèm')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú diễn giải')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_histories', to='info.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_histories', to='hrm.employee')),
                ('new_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hrm.department')),
                ('new_designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hrm.designation')),
                ('old_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hrm.department')),
                ('old_designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hrm.designation')),
            ],
            options={
                'ordering': ['-effective_date', '-create_at'],
            },
        ),
    ]
