# Generated by Django 4.2.30 on 2026-09-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0007_employeedocument_employeecareerhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dependents_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Số người phụ thuộc'),
        ),
        migrations.AlterField(
            model_name='employeecareerhistory',
            name='event_type',
            field=models.CharField(choices=[('ONBOARDING', 'Tiếp nhận / Tuyển dụng mới'), ('HIRED', 'Tuyển dụng mới'), ('PROMOTION', 'Bổ nhiệm / Thăng chức'), ('TRANSFER', 'Điều chuyển phòng ban'), ('SALARY_ADJUSTMENT', 'Điều chỉnh lương'), ('SALARY_INCREASE', 'Điều chỉnh lương'), ('ROLE_CHANGE', 'Thay đổi vị trí / Chức danh'), ('DEMOTION', 'Miễn nhiệm / Giáng chức'), ('REWARD', 'Khen thưởng'), ('DISCIPLINE', 'Kỷ luật'), ('RESIGNATION', 'Thôi việc / Nghỉ việc'), ('TERMINATION', 'Chấm dứt hợp đồng')], default='TRANSFER', max_length=30, verbose_name='Loại biến động'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(choices=[('IDENTITY_CARD', 'CCCD / Hộ chiếu'), ('CCCD', 'CCCD / CMND / Hộ chiếu'), ('LABOR_CONTRACT', 'Hợp đồng lao động bản scan'), ('DEGREE_CERTIFICATE', 'Bằng cấp / Chứng chỉ chuyên môn'), ('DEGREE', 'Bằng cấp / Chứng chỉ'), ('HEALTH_CERTIFICATE', 'Giấy khám sức khỏe định kỳ'), ('HEALTH_CERT', 'Giấy khám sức khỏe'), ('TAX_DOCUMENT', 'Mã số thuế / Giảm trừ gia cảnh'), ('DECISION', 'Quyết định bổ nhiệm / khen thưởng / kỷ luật'), ('RESUME', 'Sơ yếu lý lịch'), ('OTHER', 'Tài liệu khác')], default='OTHER', max_length=30, verbose_name='Phân loại tài liệu'),
        ),
    ]
