# Generated by Django 4.2.30 on 2026-09-23 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0014_jobpost_interview_script'),
        ('info', '0014_jobseekerprofile_cover_image'),
        ('hrm', '0008_employee_dependents_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeOnboardingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('OFFER_ACCEPTED', 'Đã ký Offer Letter'), ('PREBOARDING_DOCS', 'Thu thập hồ sơ số'), ('INTERNAL_PREP', 'Chuẩn bị nội bộ'), ('DAY_ONE_WELCOME', 'Chào đón Ngày đầu (Day 1)'), ('PROBATION_EVALUATION', 'Đang thử việc & Đánh giá'), ('COMPLETED', 'Tiếp nhận thành công (Chính thức)'), ('CANCELLED', 'Hủy tiếp nhận')], db_index=True, default='PREBOARDING_DOCS', max_length=30, verbose_name='Chặng quy trình')),
                ('target_start_date', models.DateField(blank=True, null=True, verbose_name='Ngày nhận việc dự kiến')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='Ngày nhận việc thực tế')),
                ('probation_end_date', models.DateField(blank=True, null=True, verbose_name='Hạn kết thúc thử việc')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Tiến độ hoàn thành %')),
                ('cancel_reason', models.TextField(blank=True, default='', verbose_name='Lý do hủy tiếp nhận')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_processes', to='job.jobpostactivity')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_processes', to='info.company')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_process', to='hrm.employee')),
                ('offer_letter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_process', to='job.jobofferletter')),
            ],
            options={
                'verbose_name': 'Quy trình Onboarding',
                'verbose_name_plural': 'Các quy trình Onboarding',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('OFFER_ACCEPTED', 'Đã ký Offer Letter'), ('PREBOARDING_DOCS', 'Thu thập hồ sơ số'), ('INTERNAL_PREP', 'Chuẩn bị nội bộ'), ('DAY_ONE_WELCOME', 'Chào đón Ngày đầu (Day 1)'), ('PROBATION_EVALUATION', 'Đang thử việc & Đánh giá'), ('COMPLETED', 'Tiếp nhận thành công (Chính thức)'), ('CANCELLED', 'Hủy tiếp nhận')], max_length=30, verbose_name='Thuộc chặng')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='Mã công việc')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề công việc')),
                ('description', models.TextField(blank=True, default='', verbose_name='Mô tả công việc')),
                ('assigned_role', models.CharField(choices=[('CANDIDATE', 'Ứng viên / Nhân viên mới'), ('HR', 'Quản trị nhân sự (HR)'), ('IT', 'Kỹ thuật / IT Support'), ('MANAGER', 'Quản lý trực tiếp')], default='HR', max_length=20, verbose_name='Vai trò phụ trách')),
                ('is_required', models.BooleanField(default=True, verbose_name='Bắt buộc')),
                ('is_completed', models.BooleanField(db_index=True, default=False, verbose_name='Đã hoàn thành')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm hoàn thành')),
                ('rejection_note', models.TextField(blank=True, default='', verbose_name='Ghi chú yêu cầu nộp lại')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_onboarding_tasks', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_onboarding_tasks', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hrm.employeedocument', verbose_name='Tài liệu liên kết')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='hrm.employeeonboardingprocess')),
            ],
            options={
                'verbose_name': 'Nhiệm vụ Onboarding',
                'verbose_name_plural': 'Các nhiệm vụ Onboarding',
                'ordering': ['order', 'id'],
            },
        ),
    ]
